// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api_proto/common.proto

package monorail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Next available tag: 9
type FieldType int32

const (
	FieldType_NO_TYPE       FieldType = 0
	FieldType_ENUM_TYPE     FieldType = 1
	FieldType_INT_TYPE      FieldType = 2
	FieldType_STR_TYPE      FieldType = 3
	FieldType_USER_TYPE     FieldType = 4
	FieldType_DATE_TYPE     FieldType = 5
	FieldType_BOOL_TYPE     FieldType = 6
	FieldType_URL_TYPE      FieldType = 7
	FieldType_APPROVAL_TYPE FieldType = 8
)

var FieldType_name = map[int32]string{
	0: "NO_TYPE",
	1: "ENUM_TYPE",
	2: "INT_TYPE",
	3: "STR_TYPE",
	4: "USER_TYPE",
	5: "DATE_TYPE",
	6: "BOOL_TYPE",
	7: "URL_TYPE",
	8: "APPROVAL_TYPE",
}

var FieldType_value = map[string]int32{
	"NO_TYPE":       0,
	"ENUM_TYPE":     1,
	"INT_TYPE":      2,
	"STR_TYPE":      3,
	"USER_TYPE":     4,
	"DATE_TYPE":     5,
	"BOOL_TYPE":     6,
	"URL_TYPE":      7,
	"APPROVAL_TYPE": 8,
}

func (x FieldType) String() string {
	return proto.EnumName(FieldType_name, int32(x))
}

func (FieldType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{0}
}

// Next available tag: 3
type ComponentRef struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDerived            bool     `protobuf:"varint,2,opt,name=is_derived,json=isDerived,proto3" json:"is_derived,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComponentRef) Reset()         { *m = ComponentRef{} }
func (m *ComponentRef) String() string { return proto.CompactTextString(m) }
func (*ComponentRef) ProtoMessage()    {}
func (*ComponentRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{0}
}

func (m *ComponentRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentRef.Unmarshal(m, b)
}
func (m *ComponentRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentRef.Marshal(b, m, deterministic)
}
func (m *ComponentRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentRef.Merge(m, src)
}
func (m *ComponentRef) XXX_Size() int {
	return xxx_messageInfo_ComponentRef.Size(m)
}
func (m *ComponentRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentRef.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentRef proto.InternalMessageInfo

func (m *ComponentRef) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ComponentRef) GetIsDerived() bool {
	if m != nil {
		return m.IsDerived
	}
	return false
}

// Next available tag: 5
type FieldRef struct {
	// TODO(crbug.com/monorail/4062): Don't use field IDs to identify fields.
	FieldId              uint64    `protobuf:"varint,1,opt,name=field_id,json=fieldId,proto3" json:"field_id,omitempty"`
	FieldName            string    `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	Type                 FieldType `protobuf:"varint,3,opt,name=type,proto3,enum=monorail.FieldType" json:"type,omitempty"`
	ApprovalName         string    `protobuf:"bytes,4,opt,name=approval_name,json=approvalName,proto3" json:"approval_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FieldRef) Reset()         { *m = FieldRef{} }
func (m *FieldRef) String() string { return proto.CompactTextString(m) }
func (*FieldRef) ProtoMessage()    {}
func (*FieldRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{1}
}

func (m *FieldRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldRef.Unmarshal(m, b)
}
func (m *FieldRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldRef.Marshal(b, m, deterministic)
}
func (m *FieldRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldRef.Merge(m, src)
}
func (m *FieldRef) XXX_Size() int {
	return xxx_messageInfo_FieldRef.Size(m)
}
func (m *FieldRef) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldRef.DiscardUnknown(m)
}

var xxx_messageInfo_FieldRef proto.InternalMessageInfo

func (m *FieldRef) GetFieldId() uint64 {
	if m != nil {
		return m.FieldId
	}
	return 0
}

func (m *FieldRef) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *FieldRef) GetType() FieldType {
	if m != nil {
		return m.Type
	}
	return FieldType_NO_TYPE
}

func (m *FieldRef) GetApprovalName() string {
	if m != nil {
		return m.ApprovalName
	}
	return ""
}

// Next available tag: 3
type LabelRef struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	IsDerived            bool     `protobuf:"varint,2,opt,name=is_derived,json=isDerived,proto3" json:"is_derived,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelRef) Reset()         { *m = LabelRef{} }
func (m *LabelRef) String() string { return proto.CompactTextString(m) }
func (*LabelRef) ProtoMessage()    {}
func (*LabelRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{2}
}

func (m *LabelRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelRef.Unmarshal(m, b)
}
func (m *LabelRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelRef.Marshal(b, m, deterministic)
}
func (m *LabelRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelRef.Merge(m, src)
}
func (m *LabelRef) XXX_Size() int {
	return xxx_messageInfo_LabelRef.Size(m)
}
func (m *LabelRef) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelRef.DiscardUnknown(m)
}

var xxx_messageInfo_LabelRef proto.InternalMessageInfo

func (m *LabelRef) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *LabelRef) GetIsDerived() bool {
	if m != nil {
		return m.IsDerived
	}
	return false
}

// Next available tag: 4
type StatusRef struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MeansOpen            bool     `protobuf:"varint,2,opt,name=means_open,json=meansOpen,proto3" json:"means_open,omitempty"`
	IsDerived            bool     `protobuf:"varint,3,opt,name=is_derived,json=isDerived,proto3" json:"is_derived,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRef) Reset()         { *m = StatusRef{} }
func (m *StatusRef) String() string { return proto.CompactTextString(m) }
func (*StatusRef) ProtoMessage()    {}
func (*StatusRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{3}
}

func (m *StatusRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRef.Unmarshal(m, b)
}
func (m *StatusRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRef.Marshal(b, m, deterministic)
}
func (m *StatusRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRef.Merge(m, src)
}
func (m *StatusRef) XXX_Size() int {
	return xxx_messageInfo_StatusRef.Size(m)
}
func (m *StatusRef) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRef.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRef proto.InternalMessageInfo

func (m *StatusRef) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StatusRef) GetMeansOpen() bool {
	if m != nil {
		return m.MeansOpen
	}
	return false
}

func (m *StatusRef) GetIsDerived() bool {
	if m != nil {
		return m.IsDerived
	}
	return false
}

// Next available tag: 4
type IssueRef struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	LocalId              uint32   `protobuf:"varint,2,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	ExtIdentifier        string   `protobuf:"bytes,3,opt,name=ext_identifier,json=extIdentifier,proto3" json:"ext_identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueRef) Reset()         { *m = IssueRef{} }
func (m *IssueRef) String() string { return proto.CompactTextString(m) }
func (*IssueRef) ProtoMessage()    {}
func (*IssueRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{4}
}

func (m *IssueRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueRef.Unmarshal(m, b)
}
func (m *IssueRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueRef.Marshal(b, m, deterministic)
}
func (m *IssueRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueRef.Merge(m, src)
}
func (m *IssueRef) XXX_Size() int {
	return xxx_messageInfo_IssueRef.Size(m)
}
func (m *IssueRef) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueRef.DiscardUnknown(m)
}

var xxx_messageInfo_IssueRef proto.InternalMessageInfo

func (m *IssueRef) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *IssueRef) GetLocalId() uint32 {
	if m != nil {
		return m.LocalId
	}
	return 0
}

func (m *IssueRef) GetExtIdentifier() string {
	if m != nil {
		return m.ExtIdentifier
	}
	return ""
}

// Next available tag: 4
type UserRef struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsDerived            bool     `protobuf:"varint,3,opt,name=is_derived,json=isDerived,proto3" json:"is_derived,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRef) Reset()         { *m = UserRef{} }
func (m *UserRef) String() string { return proto.CompactTextString(m) }
func (*UserRef) ProtoMessage()    {}
func (*UserRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{5}
}

func (m *UserRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRef.Unmarshal(m, b)
}
func (m *UserRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRef.Marshal(b, m, deterministic)
}
func (m *UserRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRef.Merge(m, src)
}
func (m *UserRef) XXX_Size() int {
	return xxx_messageInfo_UserRef.Size(m)
}
func (m *UserRef) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRef.DiscardUnknown(m)
}

var xxx_messageInfo_UserRef proto.InternalMessageInfo

func (m *UserRef) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserRef) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserRef) GetIsDerived() bool {
	if m != nil {
		return m.IsDerived
	}
	return false
}

// Next available tag: 4
type HotlistRef struct {
	// TODO(4131): Don't use hotlist IDs to identify hotlists.
	HotlistId            uint64   `protobuf:"varint,1,opt,name=hotlist_id,json=hotlistId,proto3" json:"hotlist_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                *UserRef `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotlistRef) Reset()         { *m = HotlistRef{} }
func (m *HotlistRef) String() string { return proto.CompactTextString(m) }
func (*HotlistRef) ProtoMessage()    {}
func (*HotlistRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{6}
}

func (m *HotlistRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotlistRef.Unmarshal(m, b)
}
func (m *HotlistRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotlistRef.Marshal(b, m, deterministic)
}
func (m *HotlistRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotlistRef.Merge(m, src)
}
func (m *HotlistRef) XXX_Size() int {
	return xxx_messageInfo_HotlistRef.Size(m)
}
func (m *HotlistRef) XXX_DiscardUnknown() {
	xxx_messageInfo_HotlistRef.DiscardUnknown(m)
}

var xxx_messageInfo_HotlistRef proto.InternalMessageInfo

func (m *HotlistRef) GetHotlistId() uint64 {
	if m != nil {
		return m.HotlistId
	}
	return 0
}

func (m *HotlistRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HotlistRef) GetOwner() *UserRef {
	if m != nil {
		return m.Owner
	}
	return nil
}

// Next available tag: 3
type ValueAndWhy struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Why                  string   `protobuf:"bytes,2,opt,name=why,proto3" json:"why,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueAndWhy) Reset()         { *m = ValueAndWhy{} }
func (m *ValueAndWhy) String() string { return proto.CompactTextString(m) }
func (*ValueAndWhy) ProtoMessage()    {}
func (*ValueAndWhy) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{7}
}

func (m *ValueAndWhy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueAndWhy.Unmarshal(m, b)
}
func (m *ValueAndWhy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueAndWhy.Marshal(b, m, deterministic)
}
func (m *ValueAndWhy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueAndWhy.Merge(m, src)
}
func (m *ValueAndWhy) XXX_Size() int {
	return xxx_messageInfo_ValueAndWhy.Size(m)
}
func (m *ValueAndWhy) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueAndWhy.DiscardUnknown(m)
}

var xxx_messageInfo_ValueAndWhy proto.InternalMessageInfo

func (m *ValueAndWhy) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ValueAndWhy) GetWhy() string {
	if m != nil {
		return m.Why
	}
	return ""
}

// Next available tag: 3
type Pagination struct {
	MaxItems             uint32   `protobuf:"varint,1,opt,name=max_items,json=maxItems,proto3" json:"max_items,omitempty"`
	Start                uint32   `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{8}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetMaxItems() uint32 {
	if m != nil {
		return m.MaxItems
	}
	return 0
}

func (m *Pagination) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

// Next available tag: 5
type SavedQuery struct {
	QueryId              uint64   `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	ProjectNames         []string `protobuf:"bytes,4,rep,name=project_names,json=projectNames,proto3" json:"project_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavedQuery) Reset()         { *m = SavedQuery{} }
func (m *SavedQuery) String() string { return proto.CompactTextString(m) }
func (*SavedQuery) ProtoMessage()    {}
func (*SavedQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_d57a37ef5e3928fa, []int{9}
}

func (m *SavedQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedQuery.Unmarshal(m, b)
}
func (m *SavedQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedQuery.Marshal(b, m, deterministic)
}
func (m *SavedQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedQuery.Merge(m, src)
}
func (m *SavedQuery) XXX_Size() int {
	return xxx_messageInfo_SavedQuery.Size(m)
}
func (m *SavedQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedQuery.DiscardUnknown(m)
}

var xxx_messageInfo_SavedQuery proto.InternalMessageInfo

func (m *SavedQuery) GetQueryId() uint64 {
	if m != nil {
		return m.QueryId
	}
	return 0
}

func (m *SavedQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SavedQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SavedQuery) GetProjectNames() []string {
	if m != nil {
		return m.ProjectNames
	}
	return nil
}

func init() {
	proto.RegisterEnum("monorail.FieldType", FieldType_name, FieldType_value)
	proto.RegisterType((*ComponentRef)(nil), "monorail.ComponentRef")
	proto.RegisterType((*FieldRef)(nil), "monorail.FieldRef")
	proto.RegisterType((*LabelRef)(nil), "monorail.LabelRef")
	proto.RegisterType((*StatusRef)(nil), "monorail.StatusRef")
	proto.RegisterType((*IssueRef)(nil), "monorail.IssueRef")
	proto.RegisterType((*UserRef)(nil), "monorail.UserRef")
	proto.RegisterType((*HotlistRef)(nil), "monorail.HotlistRef")
	proto.RegisterType((*ValueAndWhy)(nil), "monorail.ValueAndWhy")
	proto.RegisterType((*Pagination)(nil), "monorail.Pagination")
	proto.RegisterType((*SavedQuery)(nil), "monorail.SavedQuery")
}

func init() { proto.RegisterFile("api/api_proto/common.proto", fileDescriptor_d57a37ef5e3928fa) }

var fileDescriptor_d57a37ef5e3928fa = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x6f, 0x6f, 0xd3, 0x3e,
	0x10, 0xc7, 0x7f, 0x59, 0xff, 0x25, 0xd7, 0x76, 0xda, 0xfc, 0x9b, 0xa0, 0x03, 0x4d, 0x2a, 0x41,
	0x68, 0x13, 0x0f, 0x36, 0x69, 0x88, 0xc7, 0x53, 0x61, 0x45, 0x44, 0x1a, 0x6d, 0x49, 0xdb, 0x21,
	0x1e, 0x45, 0xde, 0xe2, 0x51, 0xa3, 0x24, 0x36, 0xb1, 0xdb, 0xb5, 0x2f, 0x03, 0x5e, 0x31, 0x3a,
	0xdb, 0x5d, 0xab, 0x49, 0x68, 0xcf, 0xee, 0x73, 0x8e, 0xbf, 0xdf, 0x3b, 0xdf, 0xb5, 0xf0, 0x82,
	0x4a, 0x7e, 0x46, 0x25, 0x4f, 0x64, 0x29, 0xb4, 0x38, 0xbb, 0x15, 0x79, 0x2e, 0x8a, 0x53, 0x03,
	0xc4, 0xcf, 0x45, 0x21, 0x4a, 0xca, 0xb3, 0xb0, 0x07, 0xad, 0x8f, 0x22, 0x97, 0xa2, 0x60, 0x85,
	0x8e, 0xd9, 0x1d, 0x21, 0x50, 0x95, 0x54, 0xcf, 0x3a, 0x5e, 0xd7, 0x3b, 0x09, 0x62, 0x13, 0x93,
	0x23, 0x00, 0xae, 0x92, 0x94, 0x95, 0x7c, 0xc1, 0xd2, 0xce, 0x4e, 0xd7, 0x3b, 0xf1, 0xe3, 0x80,
	0xab, 0x4b, 0x9b, 0x08, 0xff, 0x78, 0xe0, 0x7f, 0xe2, 0x2c, 0x4b, 0xf1, 0xfe, 0x21, 0xf8, 0x77,
	0x18, 0x27, 0x3c, 0x35, 0x1a, 0xd5, 0xb8, 0x61, 0x38, 0x4a, 0x51, 0xc6, 0x1e, 0x15, 0x34, 0x67,
	0x46, 0x26, 0x88, 0x03, 0x93, 0x19, 0xd0, 0x9c, 0x91, 0x63, 0xa8, 0xea, 0x95, 0x64, 0x9d, 0x4a,
	0xd7, 0x3b, 0xd9, 0x3d, 0xff, 0xff, 0x74, 0x5d, 0xe2, 0xa9, 0xd1, 0x9e, 0xac, 0x24, 0x8b, 0xcd,
	0x07, 0xe4, 0x35, 0xb4, 0xa9, 0x94, 0xa5, 0x58, 0xd0, 0xcc, 0x4a, 0x55, 0x8d, 0x54, 0x6b, 0x9d,
	0x44, 0xb5, 0xf0, 0x02, 0xfc, 0x2b, 0x7a, 0xc3, 0x32, 0xac, 0xe9, 0x00, 0x6a, 0x19, 0xc6, 0xae,
	0x29, 0x0b, 0x4f, 0x75, 0x45, 0x21, 0x18, 0x6b, 0xaa, 0xe7, 0x0a, 0x15, 0x9e, 0x41, 0x5d, 0x19,
	0x70, 0x12, 0x8e, 0x50, 0x23, 0x67, 0xb4, 0x50, 0x89, 0x90, 0xac, 0x58, 0x6b, 0x98, 0xcc, 0x50,
	0xb2, 0xe2, 0x91, 0x45, 0xe5, 0xb1, 0x85, 0x00, 0x3f, 0x52, 0x6a, 0xce, 0xd0, 0xe1, 0x15, 0xb4,
	0x64, 0x29, 0x7e, 0xb2, 0x5b, 0x6d, 0x7b, 0xb2, 0x3e, 0x4d, 0x97, 0x33, 0x0f, 0x74, 0x08, 0x7e,
	0x26, 0x6e, 0x69, 0x86, 0x4f, 0x8b, 0x56, 0xed, 0xb8, 0x61, 0x38, 0x4a, 0xc9, 0x1b, 0xd8, 0x65,
	0x4b, 0x9d, 0xf0, 0x94, 0x15, 0x9a, 0xdf, 0x71, 0x56, 0x1a, 0xb3, 0x20, 0x6e, 0xb3, 0xa5, 0x8e,
	0x1e, 0x92, 0x61, 0x0a, 0x8d, 0xa9, 0x62, 0x25, 0xfa, 0x3d, 0x87, 0xc6, 0x5c, 0xb1, 0x72, 0x33,
	0xa6, 0x3a, 0x62, 0x94, 0x62, 0x21, 0x29, 0x57, 0x32, 0xa3, 0xab, 0xed, 0x39, 0x35, 0x5d, 0xce,
	0x14, 0xf2, 0x44, 0x5b, 0x33, 0x80, 0xcf, 0x42, 0x67, 0x5c, 0x99, 0x85, 0x3a, 0x02, 0x98, 0x59,
	0xda, 0x78, 0x05, 0x2e, 0x13, 0xa5, 0xb8, 0x6f, 0x5b, 0x36, 0x26, 0x26, 0xc7, 0x50, 0x13, 0xf7,
	0x85, 0x6b, 0xa2, 0x79, 0xbe, 0xbf, 0x59, 0x05, 0x57, 0x7d, 0x6c, 0xcf, 0xc3, 0xf7, 0xd0, 0xbc,
	0xa6, 0xd9, 0x9c, 0xf5, 0x8a, 0xf4, 0xdb, 0x6c, 0x85, 0x73, 0x5e, 0x20, 0xae, 0xe7, 0x6c, 0x80,
	0xec, 0x41, 0xe5, 0x7e, 0xb6, 0x72, 0x06, 0x18, 0x86, 0x17, 0x00, 0x23, 0xfa, 0x83, 0x17, 0x54,
	0x73, 0x51, 0x90, 0x97, 0x10, 0xe4, 0x74, 0x99, 0x70, 0xcd, 0x72, 0x3b, 0xde, 0x76, 0xec, 0xe7,
	0x74, 0x19, 0x21, 0xa3, 0xa4, 0xd2, 0xb4, 0xd4, 0xee, 0xc1, 0x2d, 0x84, 0x0b, 0x80, 0x31, 0x5d,
	0xb0, 0xf4, 0xeb, 0x9c, 0x95, 0x2b, 0x9c, 0xcb, 0x2f, 0x0c, 0xb6, 0x56, 0xde, 0xf0, 0x3f, 0xba,
	0x3b, 0x80, 0x9a, 0x39, 0x76, 0x23, 0xb2, 0x80, 0x4b, 0xbd, 0x3d, 0x7f, 0xd5, 0xa9, 0x76, 0x2b,
	0xb8, 0xd4, 0x5b, 0x0b, 0xa0, 0xde, 0xfe, 0xf6, 0x20, 0x78, 0xf8, 0x35, 0x90, 0x26, 0x34, 0x06,
	0xc3, 0x64, 0xf2, 0x7d, 0xd4, 0xdf, 0xfb, 0x8f, 0xb4, 0x21, 0xe8, 0x0f, 0xa6, 0x5f, 0x2c, 0x7a,
	0xa4, 0x05, 0x7e, 0x34, 0x98, 0x58, 0xda, 0x41, 0x1a, 0x4f, 0x62, 0x4b, 0x15, 0xfc, 0x74, 0x3a,
	0xee, 0x3b, 0xac, 0x22, 0x5e, 0xf6, 0x26, 0x7d, 0x8b, 0x35, 0xc4, 0x0f, 0xc3, 0xe1, 0x95, 0xc5,
	0x3a, 0x5e, 0x9d, 0xc6, 0x8e, 0x1a, 0x64, 0x1f, 0xda, 0xbd, 0xd1, 0x28, 0x1e, 0x5e, 0xf7, 0x5c,
	0xca, 0xbf, 0xa9, 0x9b, 0x7f, 0x94, 0x77, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xca, 0x1f, 0x1e,
	0x9d, 0x6f, 0x04, 0x00, 0x00,
}
