// Code generated by protoc-gen-go.
// source: infra/tricium/api/admin/v1/tracker.proto
// DO NOT EDIT!

package admin

import prpc "github.com/luci/luci-go/grpc/prpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// WorkflowLaunchedRequest specified details need to mark a workflow as
// launched.
//
// This message should be sent by the Launcher after a workflow has been launched.
type WorkflowLaunchedRequest struct {
	RunId int64 `protobuf:"varint,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
}

func (m *WorkflowLaunchedRequest) Reset()                    { *m = WorkflowLaunchedRequest{} }
func (m *WorkflowLaunchedRequest) String() string            { return proto.CompactTextString(m) }
func (*WorkflowLaunchedRequest) ProtoMessage()               {}
func (*WorkflowLaunchedRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *WorkflowLaunchedRequest) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

type WorkflowLaunchedResponse struct {
}

func (m *WorkflowLaunchedResponse) Reset()                    { *m = WorkflowLaunchedResponse{} }
func (m *WorkflowLaunchedResponse) String() string            { return proto.CompactTextString(m) }
func (*WorkflowLaunchedResponse) ProtoMessage()               {}
func (*WorkflowLaunchedResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

// WorkerLaunchedRequest specifies details needed to mark a worker as launched.
// This includes details useful for the tracking UI.
//
// This message should be sent by the Driver after a swarming task for a worker
// has been triggered.
type WorkerLaunchedRequest struct {
	RunId             int64  `protobuf:"varint,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	Worker            string `protobuf:"bytes,2,opt,name=worker" json:"worker,omitempty"`
	IsolateServerUrl  string `protobuf:"bytes,3,opt,name=isolate_server_url,json=isolateServerUrl" json:"isolate_server_url,omitempty"`
	IsolatedInputHash string `protobuf:"bytes,4,opt,name=isolated_input_hash,json=isolatedInputHash" json:"isolated_input_hash,omitempty"`
	SwarmingServerUrl string `protobuf:"bytes,5,opt,name=swarming_server_url,json=swarmingServerUrl" json:"swarming_server_url,omitempty"`
	TaskId            string `protobuf:"bytes,6,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
}

func (m *WorkerLaunchedRequest) Reset()                    { *m = WorkerLaunchedRequest{} }
func (m *WorkerLaunchedRequest) String() string            { return proto.CompactTextString(m) }
func (*WorkerLaunchedRequest) ProtoMessage()               {}
func (*WorkerLaunchedRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *WorkerLaunchedRequest) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

func (m *WorkerLaunchedRequest) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *WorkerLaunchedRequest) GetIsolateServerUrl() string {
	if m != nil {
		return m.IsolateServerUrl
	}
	return ""
}

func (m *WorkerLaunchedRequest) GetIsolatedInputHash() string {
	if m != nil {
		return m.IsolatedInputHash
	}
	return ""
}

func (m *WorkerLaunchedRequest) GetSwarmingServerUrl() string {
	if m != nil {
		return m.SwarmingServerUrl
	}
	return ""
}

func (m *WorkerLaunchedRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type WorkerLaunchedResponse struct {
}

func (m *WorkerLaunchedResponse) Reset()                    { *m = WorkerLaunchedResponse{} }
func (m *WorkerLaunchedResponse) String() string            { return proto.CompactTextString(m) }
func (*WorkerLaunchedResponse) ProtoMessage()               {}
func (*WorkerLaunchedResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

// WorkerDoneRequest specifies details needed to mark a worker as done.
// This includes details useful for the tracking UI.
//
// This message should be sent by the Driver after results from the swarming
// task for a worker has been collected.
type WorkerDoneRequest struct {
	RunId              int64  `protobuf:"varint,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	Worker             string `protobuf:"bytes,2,opt,name=worker" json:"worker,omitempty"`
	IsolateServerUrl   string `protobuf:"bytes,3,opt,name=isolate_server_url,json=isolateServerUrl" json:"isolate_server_url,omitempty"`
	IsolatedOutputHash string `protobuf:"bytes,4,opt,name=isolated_output_hash,json=isolatedOutputHash" json:"isolated_output_hash,omitempty"`
	ExitCode           int64  `protobuf:"varint,5,opt,name=exit_code,json=exitCode" json:"exit_code,omitempty"`
}

func (m *WorkerDoneRequest) Reset()                    { *m = WorkerDoneRequest{} }
func (m *WorkerDoneRequest) String() string            { return proto.CompactTextString(m) }
func (*WorkerDoneRequest) ProtoMessage()               {}
func (*WorkerDoneRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *WorkerDoneRequest) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

func (m *WorkerDoneRequest) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

func (m *WorkerDoneRequest) GetIsolateServerUrl() string {
	if m != nil {
		return m.IsolateServerUrl
	}
	return ""
}

func (m *WorkerDoneRequest) GetIsolatedOutputHash() string {
	if m != nil {
		return m.IsolatedOutputHash
	}
	return ""
}

func (m *WorkerDoneRequest) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

type WorkerDoneResponse struct {
}

func (m *WorkerDoneResponse) Reset()                    { *m = WorkerDoneResponse{} }
func (m *WorkerDoneResponse) String() string            { return proto.CompactTextString(m) }
func (*WorkerDoneResponse) ProtoMessage()               {}
func (*WorkerDoneResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func init() {
	proto.RegisterType((*WorkflowLaunchedRequest)(nil), "admin.WorkflowLaunchedRequest")
	proto.RegisterType((*WorkflowLaunchedResponse)(nil), "admin.WorkflowLaunchedResponse")
	proto.RegisterType((*WorkerLaunchedRequest)(nil), "admin.WorkerLaunchedRequest")
	proto.RegisterType((*WorkerLaunchedResponse)(nil), "admin.WorkerLaunchedResponse")
	proto.RegisterType((*WorkerDoneRequest)(nil), "admin.WorkerDoneRequest")
	proto.RegisterType((*WorkerDoneResponse)(nil), "admin.WorkerDoneResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Tracker service

type TrackerClient interface {
	// WorkflowLaunched marks the workflow as launched for a specificed run.
	WorkflowLaunched(ctx context.Context, in *WorkflowLaunchedRequest, opts ...grpc.CallOption) (*WorkflowLaunchedResponse, error)
	// WorkerLaunched marks the specified worker as launched.
	WorkerLaunched(ctx context.Context, in *WorkerLaunchedRequest, opts ...grpc.CallOption) (*WorkerLaunchedResponse, error)
	// WorkerDone marks the specified worker as done.
	WorkerDone(ctx context.Context, in *WorkerDoneRequest, opts ...grpc.CallOption) (*WorkerDoneResponse, error)
}
type trackerPRPCClient struct {
	client *prpc.Client
}

func NewTrackerPRPCClient(client *prpc.Client) TrackerClient {
	return &trackerPRPCClient{client}
}

func (c *trackerPRPCClient) WorkflowLaunched(ctx context.Context, in *WorkflowLaunchedRequest, opts ...grpc.CallOption) (*WorkflowLaunchedResponse, error) {
	out := new(WorkflowLaunchedResponse)
	err := c.client.Call(ctx, "admin.Tracker", "WorkflowLaunched", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerPRPCClient) WorkerLaunched(ctx context.Context, in *WorkerLaunchedRequest, opts ...grpc.CallOption) (*WorkerLaunchedResponse, error) {
	out := new(WorkerLaunchedResponse)
	err := c.client.Call(ctx, "admin.Tracker", "WorkerLaunched", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerPRPCClient) WorkerDone(ctx context.Context, in *WorkerDoneRequest, opts ...grpc.CallOption) (*WorkerDoneResponse, error) {
	out := new(WorkerDoneResponse)
	err := c.client.Call(ctx, "admin.Tracker", "WorkerDone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type trackerClient struct {
	cc *grpc.ClientConn
}

func NewTrackerClient(cc *grpc.ClientConn) TrackerClient {
	return &trackerClient{cc}
}

func (c *trackerClient) WorkflowLaunched(ctx context.Context, in *WorkflowLaunchedRequest, opts ...grpc.CallOption) (*WorkflowLaunchedResponse, error) {
	out := new(WorkflowLaunchedResponse)
	err := grpc.Invoke(ctx, "/admin.Tracker/WorkflowLaunched", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerClient) WorkerLaunched(ctx context.Context, in *WorkerLaunchedRequest, opts ...grpc.CallOption) (*WorkerLaunchedResponse, error) {
	out := new(WorkerLaunchedResponse)
	err := grpc.Invoke(ctx, "/admin.Tracker/WorkerLaunched", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trackerClient) WorkerDone(ctx context.Context, in *WorkerDoneRequest, opts ...grpc.CallOption) (*WorkerDoneResponse, error) {
	out := new(WorkerDoneResponse)
	err := grpc.Invoke(ctx, "/admin.Tracker/WorkerDone", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tracker service

type TrackerServer interface {
	// WorkflowLaunched marks the workflow as launched for a specificed run.
	WorkflowLaunched(context.Context, *WorkflowLaunchedRequest) (*WorkflowLaunchedResponse, error)
	// WorkerLaunched marks the specified worker as launched.
	WorkerLaunched(context.Context, *WorkerLaunchedRequest) (*WorkerLaunchedResponse, error)
	// WorkerDone marks the specified worker as done.
	WorkerDone(context.Context, *WorkerDoneRequest) (*WorkerDoneResponse, error)
}

func RegisterTrackerServer(s prpc.Registrar, srv TrackerServer) {
	s.RegisterService(&_Tracker_serviceDesc, srv)
}

func _Tracker_WorkflowLaunched_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowLaunchedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServer).WorkflowLaunched(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Tracker/WorkflowLaunched",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServer).WorkflowLaunched(ctx, req.(*WorkflowLaunchedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tracker_WorkerLaunched_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerLaunchedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServer).WorkerLaunched(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Tracker/WorkerLaunched",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServer).WorkerLaunched(ctx, req.(*WorkerLaunchedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tracker_WorkerDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrackerServer).WorkerDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.Tracker/WorkerDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrackerServer).WorkerDone(ctx, req.(*WorkerDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tracker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "admin.Tracker",
	HandlerType: (*TrackerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorkflowLaunched",
			Handler:    _Tracker_WorkflowLaunched_Handler,
		},
		{
			MethodName: "WorkerLaunched",
			Handler:    _Tracker_WorkerLaunched_Handler,
		},
		{
			MethodName: "WorkerDone",
			Handler:    _Tracker_WorkerDone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infra/tricium/api/admin/v1/tracker.proto",
}

func init() { proto.RegisterFile("infra/tricium/api/admin/v1/tracker.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xcb, 0x8e, 0xda, 0x30,
	0x18, 0x85, 0x95, 0x52, 0x42, 0xf9, 0x17, 0x15, 0xb8, 0x5c, 0xd2, 0xf4, 0x86, 0xb2, 0x62, 0x51,
	0x25, 0xb4, 0x7d, 0x82, 0xaa, 0x5d, 0x14, 0xa9, 0x55, 0xa5, 0xd0, 0xaa, 0xcb, 0xc8, 0x8d, 0xcd,
	0xc4, 0x22, 0xd8, 0x19, 0x5f, 0x60, 0xde, 0x6e, 0x9e, 0x68, 0xa4, 0x79, 0x84, 0x51, 0x9c, 0x30,
	0x04, 0x18, 0xa4, 0x59, 0xcd, 0xd2, 0xff, 0x77, 0x7c, 0xf0, 0x7f, 0x38, 0x81, 0x29, 0xe3, 0x4b,
	0x89, 0x23, 0x2d, 0x59, 0xca, 0xcc, 0x3a, 0xc2, 0x05, 0x8b, 0x30, 0x59, 0x33, 0x1e, 0x6d, 0x3e,
	0x45, 0x5a, 0xe2, 0x74, 0x45, 0x65, 0x58, 0x48, 0xa1, 0x05, 0x6a, 0xdb, 0x79, 0x30, 0x83, 0xf1,
	0x3f, 0x21, 0x57, 0xcb, 0x5c, 0x6c, 0x7f, 0x62, 0xc3, 0xd3, 0x8c, 0x92, 0x98, 0x5e, 0x1a, 0xaa,
	0x34, 0x1a, 0x82, 0x2b, 0x0d, 0x4f, 0x18, 0xf1, 0x9c, 0x89, 0x33, 0x6d, 0xc5, 0x6d, 0x69, 0xf8,
	0x9c, 0x04, 0x3e, 0x78, 0xa7, 0x37, 0x54, 0x21, 0xb8, 0xa2, 0xc1, 0x8d, 0x03, 0xc3, 0x12, 0x52,
	0xf9, 0x38, 0x33, 0x34, 0x02, 0x77, 0x6b, 0xf5, 0xde, 0xb3, 0x89, 0x33, 0xed, 0xc6, 0xf5, 0x09,
	0x7d, 0x04, 0xc4, 0x94, 0xc8, 0xb1, 0xa6, 0x89, 0xa2, 0x72, 0x43, 0x65, 0x62, 0x64, 0xee, 0xb5,
	0xac, 0xa6, 0x57, 0x93, 0x85, 0x05, 0x7f, 0x65, 0x8e, 0x42, 0x78, 0x55, 0xcf, 0x48, 0xc2, 0x78,
	0x61, 0x74, 0x92, 0x61, 0x95, 0x79, 0xcf, 0xad, 0xbc, 0xbf, 0x43, 0xf3, 0x92, 0xfc, 0xc0, 0x2a,
	0x2b, 0xf5, 0x6a, 0x8b, 0xe5, 0x9a, 0xf1, 0x8b, 0xa6, 0x7d, 0xbb, 0xd2, 0xef, 0xd0, 0xde, 0x7f,
	0x0c, 0x1d, 0x8d, 0xd5, 0xaa, 0x7c, 0xbd, 0x5b, 0x3d, 0xb3, 0x3c, 0xce, 0x49, 0xe0, 0xc1, 0xe8,
	0x78, 0xdd, 0x3a, 0x89, 0x6b, 0x07, 0xfa, 0x15, 0xfa, 0x2e, 0x38, 0x7d, 0x92, 0x14, 0x66, 0x30,
	0xb8, 0x4f, 0x41, 0x18, 0x7d, 0x14, 0xc3, 0xce, 0x89, 0xfc, 0xb6, 0xc8, 0xe6, 0xf0, 0x06, 0xba,
	0xf4, 0x8a, 0xe9, 0x24, 0x15, 0x84, 0xda, 0xed, 0x5b, 0xf1, 0x8b, 0x72, 0xf0, 0x4d, 0x10, 0x1a,
	0x0c, 0x00, 0x35, 0x17, 0xa8, 0xf6, 0xfa, 0x7c, 0xeb, 0x40, 0xe7, 0x4f, 0x55, 0x24, 0xb4, 0x80,
	0xde, 0x71, 0x13, 0xd0, 0xfb, 0xd0, 0xf6, 0x2a, 0x3c, 0x53, 0x2a, 0xff, 0xc3, 0x59, 0x5e, 0xfd,
	0x00, 0xfa, 0x05, 0x2f, 0x0f, 0x23, 0x45, 0x6f, 0x1b, 0x57, 0x4e, 0x8a, 0xe5, 0xbf, 0x3b, 0x43,
	0x6b, 0xbb, 0xaf, 0x00, 0xfb, 0x2d, 0x90, 0x77, 0x20, 0x6e, 0xfc, 0x33, 0xfe, 0xeb, 0x07, 0x48,
	0x65, 0xf1, 0xdf, 0xb5, 0x1f, 0xcc, 0x97, 0xbb, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xa5, 0x46,
	0xe2, 0x5c, 0x03, 0x00, 0x00,
}
