#!/usr/bin/env python
# Copyright 2015 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Entry point for running Glyco outside of a zip or a virtual env.
# Tweaks sys.path so that all packages are accessible.

import os
import sys

THIS_DIR = os.path.dirname(os.path.abspath(__file__))

if __name__ == '__main__':
  sys.path.insert(0, os.path.join(THIS_DIR, 'third_party'))
  sys.path.insert(0, THIS_DIR)

  import glucose
  glucose.main()
