// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/tricium/api/v1/tricium.proto

package tricium

import prpc "go.chromium.org/luci/grpc/prpc"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type State int32

const (
	// Pending is for when an analysis request has been received but the corresponding
	// workflow, analyzer, or workers are not running yet.
	State_PENDING State = 0
	// Running is for when the workflow, analyzer, or workers of a request have been launched
	// but have not finished.
	State_RUNNING State = 1
	// Success is for a workflow, analyzer, or worker that successfully completed.
	//
	// Success of workflows and analyzers, is aggregated from underlying analyzers and workers,
	// where full success means success is aggregated.
	State_SUCCESS State = 2
	// Failure is for a workflow, analyzer, or worker that completed with failure.
	//
	// Failure of workflows and analyzers, is aggregated from underlying analyzers and workers,
	// where any occurrence of failure means failure is aggregated.
	State_FAILURE State = 3
	// Canceled is for user canceled workflows, analyzers, and workers.
	// NB! Not supported yet.
	State_CANCELED State = 4
	// Timed out is for workers where the triggered swarming task timed out.
	// NB! Not supported yet.
	State_TIMED_OUT State = 5
)

var State_name = map[int32]string{
	0: "PENDING",
	1: "RUNNING",
	2: "SUCCESS",
	3: "FAILURE",
	4: "CANCELED",
	5: "TIMED_OUT",
}
var State_value = map[string]int32{
	"PENDING":   0,
	"RUNNING":   1,
	"SUCCESS":   2,
	"FAILURE":   3,
	"CANCELED":  4,
	"TIMED_OUT": 5,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type Consumer int32

const (
	// No consumer means progress and results can be pulled from the Tricium service API.
	//
	// This is the default value used when no consumer is configured for a project.
	Consumer_NONE Consumer = 0
	// A Gerrit consumer means the Tricium service polls Gerrit for changes and reports
	// progress updates and results to Gerrit.
	//
	// Gerrit details need to be configured for a project before the Gerrit consumer
	// option is enabled.
	//
	// Gerrit consumer details must be provided with this option.
	Consumer_GERRIT Consumer = 1
)

var Consumer_name = map[int32]string{
	0: "NONE",
	1: "GERRIT",
}
var Consumer_value = map[string]int32{
	"NONE":   0,
	"GERRIT": 1,
}

func (x Consumer) String() string {
	return proto.EnumName(Consumer_name, int32(x))
}
func (Consumer) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

// AnalyzeRequest contains the details needed for an analysis request.
type AnalyzeRequest struct {
	// Name of the project hosting the paths listed in the request. The name
	// should map to the project name as it is connected to Tricium.
	Project string `protobuf:"bytes,1,opt,name=project" json:"project,omitempty"`
	GitRef  string `protobuf:"bytes,2,opt,name=git_ref,json=gitRef" json:"git_ref,omitempty"`
	// Paths to analyze in the project. Listed from the root of the Git
	// repository.
	// TODO(emso): document path separators or add listing of path segments.
	Paths []string `protobuf:"bytes,3,rep,name=paths" json:"paths,omitempty"`
	// Consumer to send progress updates and results to.
	//
	// This field is optional. If included it will push progress and result
	// updates to the provided consumer. The selected consumer must be
	// configured for the project of the request.
	//
	// Note that progress and results can be accessed via the Tricium
	// API regardless of whether a consumer has been included in the request.
	Consumer Consumer `protobuf:"varint,4,opt,name=consumer,enum=tricium.Consumer" json:"consumer,omitempty"`
	// Gerrit details for a Gerrit consumer.
	GerritDetails *GerritConsumerDetails `protobuf:"bytes,5,opt,name=gerrit_details,json=gerritDetails" json:"gerrit_details,omitempty"`
}

func (m *AnalyzeRequest) Reset()                    { *m = AnalyzeRequest{} }
func (m *AnalyzeRequest) String() string            { return proto.CompactTextString(m) }
func (*AnalyzeRequest) ProtoMessage()               {}
func (*AnalyzeRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *AnalyzeRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *AnalyzeRequest) GetGitRef() string {
	if m != nil {
		return m.GitRef
	}
	return ""
}

func (m *AnalyzeRequest) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *AnalyzeRequest) GetConsumer() Consumer {
	if m != nil {
		return m.Consumer
	}
	return Consumer_NONE
}

func (m *AnalyzeRequest) GetGerritDetails() *GerritConsumerDetails {
	if m != nil {
		return m.GerritDetails
	}
	return nil
}

type AnalyzeResponse struct {
	// ID of the run started for this request.
	//
	// This ID can be used to track progress and request results.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
}

func (m *AnalyzeResponse) Reset()                    { *m = AnalyzeResponse{} }
func (m *AnalyzeResponse) String() string            { return proto.CompactTextString(m) }
func (*AnalyzeResponse) ProtoMessage()               {}
func (*AnalyzeResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *AnalyzeResponse) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

type ProgressRequest struct {
	// Run ID returned by an analyze request.
	//
	// This field must be provided, unless a consumer is provided below.
	// If nothing else is provided, then all known progress for the run is returned.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	// An optional analyzer name.
	//
	// If provided, only progress for the provided analyzer will be returned.
	// The analyzer name should match the name of the analyzer in the Tricium
	// configuration.
	//
	// NB! Currently not supported.
	Analyzer string `protobuf:"bytes,2,opt,name=analyzer" json:"analyzer,omitempty"`
	// Optional platform that may be provided together with an analyzer name.
	//
	// If provided, only progress for the provided analyzer and platform will be provided.
	//
	// NB! Currently not supported.
	Platform *Platform `protobuf:"bytes,3,opt,name=platform" json:"platform,omitempty"`
	// Consumer of the progress information.
	//
	// This field is optional. If included, consumer-specific fields will be considered
	// when looking up progress information and the run ID can be excluded.
	//
	// Note that if a run ID is listed and a consumer. Then the run ID will be used.
	Consumer Consumer `protobuf:"varint,4,opt,name=consumer,enum=tricium.Consumer" json:"consumer,omitempty"`
	// Gerrit details for the Gerrit consumer.
	GerritDetails *GerritConsumerDetails `protobuf:"bytes,5,opt,name=gerrit_details,json=gerritDetails" json:"gerrit_details,omitempty"`
}

func (m *ProgressRequest) Reset()                    { *m = ProgressRequest{} }
func (m *ProgressRequest) String() string            { return proto.CompactTextString(m) }
func (*ProgressRequest) ProtoMessage()               {}
func (*ProgressRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *ProgressRequest) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

func (m *ProgressRequest) GetAnalyzer() string {
	if m != nil {
		return m.Analyzer
	}
	return ""
}

func (m *ProgressRequest) GetPlatform() *Platform {
	if m != nil {
		return m.Platform
	}
	return nil
}

func (m *ProgressRequest) GetConsumer() Consumer {
	if m != nil {
		return m.Consumer
	}
	return Consumer_NONE
}

func (m *ProgressRequest) GetGerritDetails() *GerritConsumerDetails {
	if m != nil {
		return m.GerritDetails
	}
	return nil
}

type ProgressResponse struct {
	// ID of the run progress is reported for.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	// Overall state for the run provided in the progress request.
	State State `protobuf:"varint,2,opt,name=state,enum=tricium.State" json:"state,omitempty"`
	// Analyzer progress matching the requested progress report.
	//
	// For a provided run ID this corresponds to all analyzers and platforms, and
	// for any selection of these, a subset is returned.
	//
	// NB! Selection of a subset is currently not supported.
	AnalyzerProgress []*AnalyzerProgress `protobuf:"bytes,3,rep,name=analyzer_progress,json=analyzerProgress" json:"analyzer_progress,omitempty"`
}

func (m *ProgressResponse) Reset()                    { *m = ProgressResponse{} }
func (m *ProgressResponse) String() string            { return proto.CompactTextString(m) }
func (*ProgressResponse) ProtoMessage()               {}
func (*ProgressResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *ProgressResponse) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

func (m *ProgressResponse) GetState() State {
	if m != nil {
		return m.State
	}
	return State_PENDING
}

func (m *ProgressResponse) GetAnalyzerProgress() []*AnalyzerProgress {
	if m != nil {
		return m.AnalyzerProgress
	}
	return nil
}

type AnalyzerProgress struct {
	// The analyzer name.
	Analyzer string `protobuf:"bytes,1,opt,name=analyzer" json:"analyzer,omitempty"`
	// The platform for which the analyzer progress is reported.
	Platform Platform_Name `protobuf:"varint,2,opt,name=platform,enum=tricium.Platform_Name" json:"platform,omitempty"`
	// The state of the analyzer.
	//
	// For an analyzer on a specific platform this state corresponds to the state
	// of the worker, else it is the aggregated state of all workers for the analyzer.
	State State `protobuf:"varint,3,opt,name=state,enum=tricium.State" json:"state,omitempty"`
	// URL to the swarming server running tasks for the workers of the analyzer.
	SwarmingUrl string `protobuf:"bytes,4,opt,name=swarming_url,json=swarmingUrl" json:"swarming_url,omitempty"`
	// The ID of the swarming task triggered for the analyzer worker.
	SwarmingTaskId string `protobuf:"bytes,5,opt,name=swarming_task_id,json=swarmingTaskId" json:"swarming_task_id,omitempty"`
	// Number of comments.
	//
	// For analyzers that are done and produce comments.
	NumComments int32 `protobuf:"varint,6,opt,name=num_comments,json=numComments" json:"num_comments,omitempty"`
}

func (m *AnalyzerProgress) Reset()                    { *m = AnalyzerProgress{} }
func (m *AnalyzerProgress) String() string            { return proto.CompactTextString(m) }
func (*AnalyzerProgress) ProtoMessage()               {}
func (*AnalyzerProgress) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *AnalyzerProgress) GetAnalyzer() string {
	if m != nil {
		return m.Analyzer
	}
	return ""
}

func (m *AnalyzerProgress) GetPlatform() Platform_Name {
	if m != nil {
		return m.Platform
	}
	return Platform_ANY
}

func (m *AnalyzerProgress) GetState() State {
	if m != nil {
		return m.State
	}
	return State_PENDING
}

func (m *AnalyzerProgress) GetSwarmingUrl() string {
	if m != nil {
		return m.SwarmingUrl
	}
	return ""
}

func (m *AnalyzerProgress) GetSwarmingTaskId() string {
	if m != nil {
		return m.SwarmingTaskId
	}
	return ""
}

func (m *AnalyzerProgress) GetNumComments() int32 {
	if m != nil {
		return m.NumComments
	}
	return 0
}

type ResultsRequest struct {
	// Run ID returned by an analyze request.
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	// An optional analyzer name.
	//
	// If provided, only results for the provided analyzer are returned.
	// If an analyzer is being run on more than one platform then the merged
	// results of the analyzer can be returned by exclusion of a specific platform.
	//
	// NB! Currently not supported.
	Analyzer string `protobuf:"bytes,2,opt,name=analyzer" json:"analyzer,omitempty"`
	// Optional platform that can be provided together with an analyzer name.
	//
	// If provided, only results for the provided platform and analyzer are returned.
	//
	// NB! Currently not supported.
	Platform Platform_Name `protobuf:"varint,3,opt,name=platform,enum=tricium.Platform_Name" json:"platform,omitempty"`
}

func (m *ResultsRequest) Reset()                    { *m = ResultsRequest{} }
func (m *ResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*ResultsRequest) ProtoMessage()               {}
func (*ResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *ResultsRequest) GetRunId() string {
	if m != nil {
		return m.RunId
	}
	return ""
}

func (m *ResultsRequest) GetAnalyzer() string {
	if m != nil {
		return m.Analyzer
	}
	return ""
}

func (m *ResultsRequest) GetPlatform() Platform_Name {
	if m != nil {
		return m.Platform
	}
	return Platform_ANY
}

type ResultsResponse struct {
	// TODO(emso): Support paging of results to deal with large number of results.
	Results *Data_Results `protobuf:"bytes,1,opt,name=results" json:"results,omitempty"`
	// Whether the returned results are merged.
	//
	// Results may be merged if a result request for an analyzer running on multiple
	// platforms was made and the request did not include a specific platform.
	// Results for a run with no specific analyzer selected will be marked as merged
	// if any included analyzer results were merged.
	IsMerged bool `protobuf:"varint,2,opt,name=is_merged,json=isMerged" json:"is_merged,omitempty"`
}

func (m *ResultsResponse) Reset()                    { *m = ResultsResponse{} }
func (m *ResultsResponse) String() string            { return proto.CompactTextString(m) }
func (*ResultsResponse) ProtoMessage()               {}
func (*ResultsResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *ResultsResponse) GetResults() *Data_Results {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ResultsResponse) GetIsMerged() bool {
	if m != nil {
		return m.IsMerged
	}
	return false
}

// Gerrit consumer details to be provided if a Gerrit consumer is specified.
type GerritConsumerDetails struct {
	// Gerrit host.
	//
	// This value must not include protocol and is assumed to not include '##'.
	//
	// This field is required.
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	// Gerrit project name.
	//
	// This value is assumed to not include '##'.
	//
	// This field is required.
	Project string `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
	// Gerrit change ID.
	//
	// This value should be a fully qualified ID on the form "<project>~<branch>~<Change-Id>",
	// where <Change-Id> is a SHA and not a lecacy change ID number.
	// Note that refs/heads can be omitted from the branch.
	//
	// Example: "myProject~master~I8473b95934b5732ac55d26311a706c9c2bde9940"
	//
	// This field is required.
	Change string `protobuf:"bytes,3,opt,name=change" json:"change,omitempty"`
	// Gerrit change revision.
	//
	// This value should be the fetch URL for a revision of a change. Note that
	// the last number of a change revision ref maps to the corresponding patch set
	// number.
	//
	// Example: "refs/changes/97/97/1"
	//
	// This field is required.
	Revision string `protobuf:"bytes,4,opt,name=revision" json:"revision,omitempty"`
}

func (m *GerritConsumerDetails) Reset()                    { *m = GerritConsumerDetails{} }
func (m *GerritConsumerDetails) String() string            { return proto.CompactTextString(m) }
func (*GerritConsumerDetails) ProtoMessage()               {}
func (*GerritConsumerDetails) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *GerritConsumerDetails) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *GerritConsumerDetails) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *GerritConsumerDetails) GetChange() string {
	if m != nil {
		return m.Change
	}
	return ""
}

func (m *GerritConsumerDetails) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func init() {
	proto.RegisterType((*AnalyzeRequest)(nil), "tricium.AnalyzeRequest")
	proto.RegisterType((*AnalyzeResponse)(nil), "tricium.AnalyzeResponse")
	proto.RegisterType((*ProgressRequest)(nil), "tricium.ProgressRequest")
	proto.RegisterType((*ProgressResponse)(nil), "tricium.ProgressResponse")
	proto.RegisterType((*AnalyzerProgress)(nil), "tricium.AnalyzerProgress")
	proto.RegisterType((*ResultsRequest)(nil), "tricium.ResultsRequest")
	proto.RegisterType((*ResultsResponse)(nil), "tricium.ResultsResponse")
	proto.RegisterType((*GerritConsumerDetails)(nil), "tricium.GerritConsumerDetails")
	proto.RegisterEnum("tricium.State", State_name, State_value)
	proto.RegisterEnum("tricium.Consumer", Consumer_name, Consumer_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Tricium service

type TriciumClient interface {
	// Analyze requests analysis of a list of paths.
	//
	// An analysis request for a list of paths in a project connected to Tricium
	// via the Tricium configuration. On success, the ID of the resulting run is
	// returned.
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// Progress requests progress information for a run.
	//
	// A run corresponds to an analyze request and is identified with a run ID.
	Progress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error)
	// Results requests analysis results from a run.
	//
	// A run corresponds to an analyze request and is identified with a run ID.
	Results(ctx context.Context, in *ResultsRequest, opts ...grpc.CallOption) (*ResultsResponse, error)
}
type triciumPRPCClient struct {
	client *prpc.Client
}

func NewTriciumPRPCClient(client *prpc.Client) TriciumClient {
	return &triciumPRPCClient{client}
}

func (c *triciumPRPCClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	out := new(AnalyzeResponse)
	err := c.client.Call(ctx, "tricium.Tricium", "Analyze", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triciumPRPCClient) Progress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error) {
	out := new(ProgressResponse)
	err := c.client.Call(ctx, "tricium.Tricium", "Progress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triciumPRPCClient) Results(ctx context.Context, in *ResultsRequest, opts ...grpc.CallOption) (*ResultsResponse, error) {
	out := new(ResultsResponse)
	err := c.client.Call(ctx, "tricium.Tricium", "Results", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type triciumClient struct {
	cc *grpc.ClientConn
}

func NewTriciumClient(cc *grpc.ClientConn) TriciumClient {
	return &triciumClient{cc}
}

func (c *triciumClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	out := new(AnalyzeResponse)
	err := grpc.Invoke(ctx, "/tricium.Tricium/Analyze", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triciumClient) Progress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error) {
	out := new(ProgressResponse)
	err := grpc.Invoke(ctx, "/tricium.Tricium/Progress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *triciumClient) Results(ctx context.Context, in *ResultsRequest, opts ...grpc.CallOption) (*ResultsResponse, error) {
	out := new(ResultsResponse)
	err := grpc.Invoke(ctx, "/tricium.Tricium/Results", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tricium service

type TriciumServer interface {
	// Analyze requests analysis of a list of paths.
	//
	// An analysis request for a list of paths in a project connected to Tricium
	// via the Tricium configuration. On success, the ID of the resulting run is
	// returned.
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	// Progress requests progress information for a run.
	//
	// A run corresponds to an analyze request and is identified with a run ID.
	Progress(context.Context, *ProgressRequest) (*ProgressResponse, error)
	// Results requests analysis results from a run.
	//
	// A run corresponds to an analyze request and is identified with a run ID.
	Results(context.Context, *ResultsRequest) (*ResultsResponse, error)
}

func RegisterTriciumServer(s prpc.Registrar, srv TriciumServer) {
	s.RegisterService(&_Tricium_serviceDesc, srv)
}

func _Tricium_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriciumServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tricium.Tricium/Analyze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriciumServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tricium_Progress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriciumServer).Progress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tricium.Tricium/Progress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriciumServer).Progress(ctx, req.(*ProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tricium_Results_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriciumServer).Results(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tricium.Tricium/Results",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriciumServer).Results(ctx, req.(*ResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tricium_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tricium.Tricium",
	HandlerType: (*TriciumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _Tricium_Analyze_Handler,
		},
		{
			MethodName: "Progress",
			Handler:    _Tricium_Progress_Handler,
		},
		{
			MethodName: "Results",
			Handler:    _Tricium_Results_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infra/tricium/api/v1/tricium.proto",
}

func init() { proto.RegisterFile("infra/tricium/api/v1/tricium.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xc1, 0x4e, 0xdb, 0x4a,
	0x14, 0xc5, 0x24, 0x8e, 0x9d, 0x1b, 0x08, 0x66, 0xf4, 0x00, 0x93, 0x27, 0xbd, 0x97, 0xe7, 0xd7,
	0x45, 0x84, 0x54, 0xa2, 0xba, 0x5b, 0xa4, 0x0a, 0x25, 0x06, 0x45, 0x02, 0x83, 0x26, 0x89, 0xd4,
	0x9d, 0x35, 0x4d, 0x26, 0xc1, 0x25, 0xb6, 0xd3, 0x99, 0x31, 0x88, 0xfe, 0x48, 0xff, 0xa8, 0xdb,
	0x7e, 0x47, 0xff, 0xa0, 0xcb, 0xca, 0xf6, 0xd8, 0x04, 0x13, 0xa1, 0x4a, 0x5d, 0x74, 0x97, 0x73,
	0xef, 0x99, 0x7b, 0xe7, 0x9c, 0x7b, 0x3d, 0x01, 0xcb, 0x0f, 0x67, 0x8c, 0x74, 0x05, 0xf3, 0x27,
	0x7e, 0x1c, 0x74, 0xc9, 0xd2, 0xef, 0xde, 0xbd, 0xc9, 0xe1, 0xf1, 0x92, 0x45, 0x22, 0x42, 0x9a,
	0x84, 0xad, 0x7f, 0xd7, 0x92, 0xa7, 0x44, 0x90, 0x8c, 0xd9, 0xfa, 0x7f, 0x2d, 0x61, 0xb9, 0x20,
	0x62, 0x16, 0x31, 0x59, 0xce, 0xfa, 0xa6, 0x40, 0xf3, 0x34, 0x24, 0x8b, 0x87, 0xcf, 0x14, 0xd3,
	0x4f, 0x31, 0xe5, 0x02, 0x99, 0xa0, 0x2d, 0x59, 0xf4, 0x91, 0x4e, 0x84, 0xa9, 0xb4, 0x95, 0x4e,
	0x1d, 0xe7, 0x10, 0x1d, 0x80, 0x36, 0xf7, 0x85, 0xc7, 0xe8, 0xcc, 0xdc, 0x4c, 0x33, 0xb5, 0xb9,
	0x2f, 0x30, 0x9d, 0xa1, 0xbf, 0x40, 0x5d, 0x12, 0x71, 0xc3, 0xcd, 0x4a, 0xbb, 0xd2, 0xa9, 0xe3,
	0x0c, 0xa0, 0xd7, 0xa0, 0x4f, 0xa2, 0x90, 0xc7, 0x01, 0x65, 0x66, 0xb5, 0xad, 0x74, 0x9a, 0xf6,
	0xee, 0x71, 0x2e, 0xa6, 0x27, 0x13, 0xb8, 0xa0, 0x20, 0x07, 0x9a, 0x73, 0xca, 0x98, 0x2f, 0xbc,
	0x29, 0x15, 0xc4, 0x5f, 0x70, 0x53, 0x6d, 0x2b, 0x9d, 0x86, 0xfd, 0x4f, 0x71, 0xe8, 0x3c, 0x4d,
	0xe7, 0x47, 0xfb, 0x19, 0x0b, 0x6f, 0x67, 0xa7, 0x24, 0xb4, 0x3a, 0xb0, 0x53, 0x08, 0xe2, 0xcb,
	0x28, 0xe4, 0x14, 0xed, 0x41, 0x8d, 0xc5, 0xa1, 0xe7, 0x4f, 0xa5, 0x20, 0x95, 0xc5, 0xe1, 0x60,
	0x6a, 0x7d, 0x57, 0x60, 0xe7, 0x9a, 0x45, 0x73, 0x46, 0x39, 0xcf, 0xc5, 0xaf, 0xa7, 0xa2, 0x16,
	0xe8, 0x24, 0x2b, 0xca, 0xa4, 0xf4, 0x02, 0x27, 0x32, 0x73, 0x53, 0xcd, 0x4a, 0x7a, 0xe3, 0x47,
	0x99, 0xd7, 0x32, 0x81, 0x0b, 0xca, 0x1f, 0x72, 0xe5, 0x8b, 0x02, 0xc6, 0xa3, 0xd6, 0x17, 0x7d,
	0x41, 0xaf, 0x40, 0xe5, 0x82, 0x08, 0x9a, 0x2a, 0x6d, 0xda, 0xcd, 0xa2, 0xd3, 0x30, 0x89, 0xe2,
	0x2c, 0x89, 0xce, 0x60, 0x37, 0xb7, 0xc0, 0x5b, 0xca, 0xca, 0xe9, 0xfc, 0x1b, 0xf6, 0x61, 0x71,
	0x42, 0x4e, 0x82, 0x15, 0xad, 0x0d, 0x52, 0x8a, 0x58, 0x3f, 0x14, 0x30, 0xca, 0xb4, 0x27, 0x7e,
	0x2b, 0x25, 0xbf, 0xed, 0x15, 0xbf, 0xb3, 0x1b, 0xee, 0x3f, 0xf3, 0xfb, 0xd8, 0x25, 0x01, 0x5d,
	0x31, 0xbd, 0x90, 0x54, 0x79, 0x49, 0xd2, 0x7f, 0xb0, 0xc5, 0xef, 0x09, 0x0b, 0xfc, 0x70, 0xee,
	0xc5, 0x6c, 0x91, 0x8e, 0xa7, 0x8e, 0x1b, 0x79, 0x6c, 0xcc, 0x16, 0xa8, 0x03, 0x46, 0x41, 0x11,
	0x84, 0xdf, 0x26, 0xe6, 0xa9, 0x29, 0xad, 0x99, 0xc7, 0x47, 0x84, 0xdf, 0x0e, 0xa6, 0x49, 0xb1,
	0x30, 0x0e, 0xbc, 0x49, 0x14, 0x04, 0x34, 0x14, 0xdc, 0xac, 0xb5, 0x95, 0x8e, 0x8a, 0x1b, 0x61,
	0x1c, 0xf4, 0x64, 0xc8, 0xba, 0x87, 0x26, 0xa6, 0x3c, 0x5e, 0x88, 0xdf, 0x59, 0x3f, 0xbb, 0xb4,
	0x7e, 0xbf, 0x60, 0x87, 0xe5, 0xc1, 0x4e, 0xd1, 0x58, 0xee, 0x42, 0x17, 0x34, 0x96, 0x85, 0xd2,
	0xd6, 0x0d, 0x7b, 0xaf, 0xa8, 0xd2, 0x4f, 0xde, 0x94, 0x9c, 0x9f, 0xb3, 0xd0, 0xdf, 0x50, 0xf7,
	0xb9, 0x17, 0x50, 0x36, 0xa7, 0xd3, 0xf4, 0x52, 0x3a, 0xd6, 0x7d, 0x7e, 0x99, 0x62, 0xeb, 0x01,
	0xf6, 0xd6, 0xae, 0x25, 0x42, 0x50, 0xbd, 0x89, 0x78, 0xfe, 0xb2, 0xa4, 0xbf, 0x57, 0x1f, 0x9c,
	0xcd, 0xa7, 0x0f, 0xce, 0x3e, 0xd4, 0x26, 0x37, 0x24, 0x9c, 0x67, 0x73, 0xab, 0x63, 0x89, 0x12,
	0x3f, 0x18, 0xbd, 0xf3, 0xb9, 0x1f, 0x85, 0x72, 0x48, 0x05, 0x3e, 0x7a, 0x0f, 0x6a, 0x3a, 0x54,
	0xd4, 0x00, 0xed, 0xda, 0x71, 0xfb, 0x03, 0xf7, 0xdc, 0xd8, 0x48, 0x00, 0x1e, 0xbb, 0x6e, 0x02,
	0x94, 0x04, 0x0c, 0xc7, 0xbd, 0x9e, 0x33, 0x1c, 0x1a, 0x9b, 0x09, 0x38, 0x3b, 0x1d, 0x5c, 0x8c,
	0xb1, 0x63, 0x54, 0xd0, 0x16, 0xe8, 0xbd, 0x53, 0xb7, 0xe7, 0x5c, 0x38, 0x7d, 0xa3, 0x8a, 0xb6,
	0xa1, 0x3e, 0x1a, 0x5c, 0x3a, 0x7d, 0xef, 0x6a, 0x3c, 0x32, 0xd4, 0xa3, 0x36, 0xe8, 0xb9, 0x1c,
	0xa4, 0x43, 0xd5, 0xbd, 0x72, 0x1d, 0x63, 0x03, 0x01, 0xd4, 0xce, 0x1d, 0x8c, 0x07, 0x23, 0x43,
	0xb1, 0xbf, 0x2a, 0xa0, 0x8d, 0x32, 0xd7, 0xd0, 0x09, 0x68, 0x72, 0xad, 0xd1, 0x41, 0xf9, 0x7b,
	0x90, 0xe3, 0x6e, 0x99, 0xcf, 0x13, 0x72, 0x1c, 0xef, 0x40, 0x2f, 0x3e, 0x86, 0x47, 0x56, 0xe9,
	0xb5, 0x6a, 0x1d, 0xae, 0xc9, 0xc8, 0x02, 0x27, 0xa0, 0xc9, 0x91, 0xad, 0xb4, 0x7f, 0xba, 0x6d,
	0x2b, 0xed, 0x4b, 0xdb, 0xf0, 0xa1, 0x96, 0xfe, 0x3b, 0xbc, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff,
	0x26, 0x29, 0xc4, 0x58, 0x92, 0x06, 0x00, 0x00,
}
