#!/usr/bin/env python
"""
This is a helper script for making pRPC API calls during local development.
"""

import argparse
import errno
import json
import logging
import urllib2


URL_BASE = 'http://localhost:8080/prpc/'


def make_call(service, method, json_body, args):
  body = json.loads(json_body)
  if args.test_account or args.xsrf_token:
    body['trace'] = {}
    body['trace']['test_account'] = args.test_account
    body['trace']['token'] = args.xsrf_token

  url = '%s%s/%s' % (URL_BASE, service, method)
  request = urllib2.Request(url)
  request.add_header('Content-Type', 'application/json')
  request.add_header('Accept', 'application/json')
  body = json.dumps(body)
  request.add_data(body)

  logging.debug('Body: %r' % body)
  try:
    contents = urllib2.urlopen(request).read()
    logging.info('Received response: %s', contents)
  except urllib2.URLError as e:
    if hasattr(e.reason, 'errno') and e.reason.errno == errno.ECONNREFUSED:
      print '[Error] Could not reach server. Is it running?'
    else:
      raise e


if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='Process some integers.')
  parser.add_argument('service', help='pRPC service name.')
  parser.add_argument('method', help='pRPC method name.')
  parser.add_argument('json_body', help='pRPC HTTP body in valid JSON.')
  parser.add_argument('--test-account',
      help='Test account to use, in the form of an email.')
  parser.add_argument('--xsrf-token', help='Custom XSRF token.')
  parser.add_argument('-v', '--verbose', action='store_true')
  args = parser.parse_args()

  if args.verbose:
    log_level = logging.DEBUG
  else:
    log_level = logging.INFO
  logging.basicConfig(format='%(levelname)s: %(message)s', level=log_level)

  make_call(args.service, args.method, args.json_body, args)
