application: sheriff-o-matic
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4_1G

handlers:
# API Endpoints.
- url: /alerts
  script: alerts.app
  secure: always

- url: /api/v1/alerts/.*
  script: alerts.app
  secure: always

- url: /alerts-history
  script: alerts_history.app
  secure: always

- url: /alerts-history/.*
  script: alerts_history.app
  secure: always

- url: /internal-alerts
  script: internal_alerts.app
  secure: always

- url: /ts-alerts
  script: ts_alerts.app
  secure: always

- url: /ts-alerts/.*
  script: ts_alerts.app
  secure: always

- url: /ts-alerts-history
  script: ts_alerts.app
  secure: always

- url: /ts-alerts-history/.*
  script: ts_alerts.app
  secure: always

- url: /banner-msg
  script: banner_msg.app
  secure: always

- url: /banner-msg-form
  script: banner_msg.app
  secure: always

- url: /api/v1/prefs
  script: user_prefs.app
  secure: always

# Static resources.
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /lib
  static_dir: lib
  secure: always

- url: /model
  static_dir: model
  secure: always

- url: /scripts
  static_dir: scripts
  secure: always

- url: /styles
  static_dir: styles
  secure: always

- url: /ui
  static_dir: ui
  secure: always

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /appengine_module
  static_dir: appengine_module
  secure: always

# Application root.
- url: /.*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*_test\.py$
- ^(.*/)?tests\.py$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- ^(.*/)?LICENSE$
- ^(.*/)?README$
- ^(.*/)?Makefile$

includes:
- components/auth
- components/static_third_party.yaml

libraries:
- name: webapp2
  version: "latest"
- name: pycrypto
  version: "latest"
- name: jinja2
  version: "latest"

