cron:
- description: LUCI config datastore cache periodic refresh
  url: /admin/config/cache/manager
  schedule: every 10 minutes
- description: tsmon house keeping
  url: /internal/cron/ts_mon/housekeeping
  schedule: every 1 minutes
- description: Prune expired assignemts
  url: /internal/cron/ts_mon/prune-expired
  schedule: every 1 hours
