// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/appengine/arquebus/app/config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config is the service-wide configuration data for Arquebus
type Config struct {
	// AccessGroup is the luci-auth group who has access to admin pages and
	// APIs.
	AccessGroup string `protobuf:"bytes,1,opt,name=access_group,json=accessGroup,proto3" json:"access_group,omitempty"`
	// The endpoint for Monorail APIs.
	MonorailHostname string `protobuf:"bytes,2,opt,name=monorail_hostname,json=monorailHostname,proto3" json:"monorail_hostname,omitempty"`
	// A list of Assigner config(s).
	Assigners []*Assigner `protobuf:"bytes,3,rep,name=assigners,proto3" json:"assigners,omitempty"`
	// The endpoint for RotaNG APIs.
	RotangHostname       string   `protobuf:"bytes,4,opt,name=rotang_hostname,json=rotangHostname,proto3" json:"rotang_hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_421d741a02045ab0, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAccessGroup() string {
	if m != nil {
		return m.AccessGroup
	}
	return ""
}

func (m *Config) GetMonorailHostname() string {
	if m != nil {
		return m.MonorailHostname
	}
	return ""
}

func (m *Config) GetAssigners() []*Assigner {
	if m != nil {
		return m.Assigners
	}
	return nil
}

func (m *Config) GetRotangHostname() string {
	if m != nil {
		return m.RotangHostname
	}
	return ""
}

// IssueQuery describes the issue query to be used for searching unassigned
// issues in Monorail.
type IssueQuery struct {
	// Free-form text query.
	Q string `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	// String name of the projects to search issues for, e.g. "chromium".
	ProjectNames         []string `protobuf:"bytes,2,rep,name=project_names,json=projectNames,proto3" json:"project_names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssueQuery) Reset()         { *m = IssueQuery{} }
func (m *IssueQuery) String() string { return proto.CompactTextString(m) }
func (*IssueQuery) ProtoMessage()    {}
func (*IssueQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_421d741a02045ab0, []int{1}
}

func (m *IssueQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssueQuery.Unmarshal(m, b)
}
func (m *IssueQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssueQuery.Marshal(b, m, deterministic)
}
func (m *IssueQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueQuery.Merge(m, src)
}
func (m *IssueQuery) XXX_Size() int {
	return xxx_messageInfo_IssueQuery.Size(m)
}
func (m *IssueQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueQuery.DiscardUnknown(m)
}

var xxx_messageInfo_IssueQuery proto.InternalMessageInfo

func (m *IssueQuery) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *IssueQuery) GetProjectNames() []string {
	if m != nil {
		return m.ProjectNames
	}
	return nil
}

// UserSource represents a single source to find a valid Monorail user to whom
// Arquebus will assign or cc issues found.
type UserSource struct {
	// Types that are valid to be assigned to From:
	//	*UserSource_Rotation
	//	*UserSource_Email
	From                 isUserSource_From `protobuf_oneof:"from"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserSource) Reset()         { *m = UserSource{} }
func (m *UserSource) String() string { return proto.CompactTextString(m) }
func (*UserSource) ProtoMessage()    {}
func (*UserSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_421d741a02045ab0, []int{2}
}

func (m *UserSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSource.Unmarshal(m, b)
}
func (m *UserSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSource.Marshal(b, m, deterministic)
}
func (m *UserSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSource.Merge(m, src)
}
func (m *UserSource) XXX_Size() int {
	return xxx_messageInfo_UserSource.Size(m)
}
func (m *UserSource) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSource.DiscardUnknown(m)
}

var xxx_messageInfo_UserSource proto.InternalMessageInfo

type isUserSource_From interface {
	isUserSource_From()
}

type UserSource_Rotation struct {
	Rotation string `protobuf:"bytes,1,opt,name=rotation,proto3,oneof"`
}

type UserSource_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*UserSource_Rotation) isUserSource_From() {}

func (*UserSource_Email) isUserSource_From() {}

func (m *UserSource) GetFrom() isUserSource_From {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *UserSource) GetRotation() string {
	if x, ok := m.GetFrom().(*UserSource_Rotation); ok {
		return x.Rotation
	}
	return ""
}

func (m *UserSource) GetEmail() string {
	if x, ok := m.GetFrom().(*UserSource_Email); ok {
		return x.Email
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UserSource) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UserSource_Rotation)(nil),
		(*UserSource_Email)(nil),
	}
}

// Assigner contains specifications for an Assigner job.
type Assigner struct {
	// The unique ID of the Assigner.
	//
	// This value will be used in URLs of UI, so keep it short. Note that
	// only lowercase alphabet letters and numbers are allowed. A hyphen may
	// be placed between letters and numbers.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// An email list of the owners of the Assigner.
	Owners []string `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
	// The duration between the start of an Assigner run and the next one.
	//
	// This value be at least a minute long.
	Interval *duration.Duration `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	// IssueQuery describes the search criteria to look for issues to assign.
	IssueQuery *IssueQuery `protobuf:"bytes,4,opt,name=issue_query,json=issueQuery,proto3" json:"issue_query,omitempty"`
	// If multiple values are specified in assignees, Arquebus iterates the list
	// in the order until it finds a currently available assignee. Note that
	// Monorail users are always assumed to be available.
	Assignees []*UserSource `protobuf:"bytes,6,rep,name=assignees,proto3" json:"assignees,omitempty"`
	// If multiple values are specified in ccs, all the available roations and
	// users are added to the CC of searched issues.
	Ccs []*UserSource `protobuf:"bytes,7,rep,name=ccs,proto3" json:"ccs,omitempty"`
	// If DryRun is set, Assigner doesn't update the found issues.
	DryRun bool `protobuf:"varint,8,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// The description shown on UI.
	Description          string   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Assigner) Reset()         { *m = Assigner{} }
func (m *Assigner) String() string { return proto.CompactTextString(m) }
func (*Assigner) ProtoMessage()    {}
func (*Assigner) Descriptor() ([]byte, []int) {
	return fileDescriptor_421d741a02045ab0, []int{3}
}

func (m *Assigner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assigner.Unmarshal(m, b)
}
func (m *Assigner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assigner.Marshal(b, m, deterministic)
}
func (m *Assigner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assigner.Merge(m, src)
}
func (m *Assigner) XXX_Size() int {
	return xxx_messageInfo_Assigner.Size(m)
}
func (m *Assigner) XXX_DiscardUnknown() {
	xxx_messageInfo_Assigner.DiscardUnknown(m)
}

var xxx_messageInfo_Assigner proto.InternalMessageInfo

func (m *Assigner) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Assigner) GetOwners() []string {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *Assigner) GetInterval() *duration.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *Assigner) GetIssueQuery() *IssueQuery {
	if m != nil {
		return m.IssueQuery
	}
	return nil
}

func (m *Assigner) GetAssignees() []*UserSource {
	if m != nil {
		return m.Assignees
	}
	return nil
}

func (m *Assigner) GetCcs() []*UserSource {
	if m != nil {
		return m.Ccs
	}
	return nil
}

func (m *Assigner) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *Assigner) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "arquebus.config.Config")
	proto.RegisterType((*IssueQuery)(nil), "arquebus.config.IssueQuery")
	proto.RegisterType((*UserSource)(nil), "arquebus.config.UserSource")
	proto.RegisterType((*Assigner)(nil), "arquebus.config.Assigner")
}

func init() {
	proto.RegisterFile("infra/appengine/arquebus/app/config/config.proto", fileDescriptor_421d741a02045ab0)
}

var fileDescriptor_421d741a02045ab0 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x37, 0xc9, 0x92, 0x4d, 0x27, 0x65, 0x17, 0x7c, 0x58, 0xc2, 0x1f, 0xa1, 0x50, 0x0e,
	0x54, 0x42, 0x24, 0x68, 0x11, 0x42, 0x48, 0x48, 0x88, 0x05, 0x89, 0xc2, 0x01, 0x09, 0x23, 0x2e,
	0x5c, 0x22, 0x37, 0x71, 0x83, 0x51, 0x6b, 0xa7, 0xe3, 0x18, 0xd4, 0x57, 0xe3, 0x19, 0x78, 0x28,
	0x14, 0x3b, 0x69, 0x10, 0x3d, 0xec, 0x29, 0xf2, 0xe7, 0x6f, 0x3c, 0x33, 0xbf, 0x2f, 0xf0, 0x54,
	0xc8, 0x15, 0xb2, 0x9c, 0x35, 0x0d, 0x97, 0xb5, 0x90, 0x3c, 0x67, 0xb8, 0x35, 0x7c, 0x69, 0x74,
	0x27, 0xe5, 0xa5, 0x92, 0x2b, 0x51, 0xf7, 0x9f, 0xac, 0x41, 0xd5, 0x2a, 0x72, 0x36, 0x38, 0x32,
	0x27, 0xdf, 0xb9, 0x5f, 0x2b, 0x55, 0xaf, 0x79, 0x6e, 0xaf, 0x97, 0x66, 0x95, 0x57, 0x06, 0x59,
	0x2b, 0x94, 0x74, 0x05, 0xb3, 0xdf, 0x1e, 0x84, 0x6f, 0xad, 0x95, 0x3c, 0x80, 0x29, 0x2b, 0x4b,
	0xae, 0x75, 0x51, 0xa3, 0x32, 0x4d, 0xe2, 0xa5, 0xde, 0x7c, 0x42, 0x63, 0xa7, 0xbd, 0xef, 0x24,
	0xf2, 0x18, 0x6e, 0x6e, 0x94, 0x54, 0xc8, 0xc4, 0xba, 0xf8, 0xae, 0x74, 0x2b, 0xd9, 0x86, 0x27,
	0xbe, 0xf5, 0xdd, 0x18, 0x2e, 0x16, 0xbd, 0x4e, 0x5e, 0xc0, 0x84, 0x69, 0x2d, 0x6a, 0xc9, 0x51,
	0x27, 0x41, 0x1a, 0xcc, 0xe3, 0x8b, 0xdb, 0xd9, 0x7f, 0xf3, 0x65, 0x6f, 0x7a, 0x07, 0x1d, 0xbd,
	0xe4, 0x11, 0x9c, 0xa1, 0x6a, 0x99, 0xac, 0xc7, 0x1e, 0xc7, 0xb6, 0xc7, 0xa9, 0x93, 0x87, 0x0e,
	0xb3, 0xd7, 0x00, 0x1f, 0xb4, 0x36, 0xfc, 0xb3, 0xe1, 0xb8, 0x23, 0x53, 0xf0, 0xb6, 0xfd, 0xd0,
	0xde, 0x96, 0x3c, 0x84, 0xeb, 0x0d, 0xaa, 0x1f, 0xbc, 0x6c, 0x8b, 0xce, 0xab, 0x13, 0x3f, 0x0d,
	0xe6, 0x13, 0x3a, 0xed, 0xc5, 0x4f, 0x9d, 0x36, 0xfb, 0x08, 0xf0, 0x55, 0x73, 0xfc, 0xa2, 0x0c,
	0x96, 0x9c, 0xdc, 0x83, 0xa8, 0x6b, 0xd0, 0xd1, 0x71, 0xef, 0x2c, 0x8e, 0xe8, 0x5e, 0x21, 0xe7,
	0x70, 0x8d, 0x6f, 0x98, 0x58, 0xbb, 0x7d, 0x17, 0x47, 0xd4, 0x1d, 0x2f, 0x43, 0x38, 0x5e, 0xa1,
	0xda, 0xcc, 0xfe, 0xf8, 0x10, 0x0d, 0xdb, 0x90, 0x53, 0xf0, 0x45, 0xd5, 0x0f, 0xe3, 0x8b, 0x8a,
	0x9c, 0x43, 0xa8, 0x7e, 0x59, 0x10, 0x6e, 0x8c, 0xfe, 0x44, 0x9e, 0x43, 0x24, 0x64, 0xcb, 0xf1,
	0x27, 0x5b, 0x27, 0x41, 0xea, 0x59, 0x44, 0x2e, 0xb1, 0x6c, 0x48, 0x2c, 0x7b, 0xd7, 0x27, 0x46,
	0xf7, 0x56, 0xf2, 0x0a, 0x62, 0xd1, 0x2d, 0x5e, 0x6c, 0xbb, 0xcd, 0x2d, 0x9d, 0xf8, 0xe2, 0xee,
	0x01, 0xdc, 0x11, 0x0e, 0x05, 0x31, 0x82, 0x7a, 0xb9, 0x0f, 0x86, 0xeb, 0x24, 0xb4, 0xc1, 0x1c,
	0xd6, 0x8e, 0x5c, 0xe8, 0xe8, 0x26, 0x4f, 0x20, 0x28, 0x4b, 0x9d, 0x9c, 0x5c, 0x5d, 0xd4, 0xf9,
	0xc8, 0x2d, 0x38, 0xa9, 0x70, 0x57, 0xa0, 0x91, 0x49, 0x94, 0x7a, 0xf3, 0x88, 0x86, 0x15, 0xee,
	0xa8, 0x91, 0x24, 0x85, 0xb8, 0xe2, 0xba, 0x44, 0xd1, 0x58, 0xda, 0x13, 0xf7, 0xab, 0xfd, 0x23,
	0x5d, 0x46, 0xdf, 0x42, 0xf7, 0xe8, 0x32, 0xb4, 0x24, 0x9e, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x34, 0x2f, 0x6d, 0x11, 0x0e, 0x03, 0x00, 0x00,
}
