application: cr-rev
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default
instance_class: F1
automatic_scaling:
  min_idle_instances: 1

handlers:
# Endpoints handler.
- url: /_ah/spi/.*
  script: appengine_module.cr_rev.cr_rev_api.APPLICATION
  secure: always

# Pipeline handler.
- url: /_ah/pipeline(/.*)?
  script: "appengine_module.pipeline_utils.\
          appengine_third_party_pipeline_python_src_pipeline.handlers._APP"
  secure: always

- url: /css
  static_dir: appengine_module/cr_rev/css
  secure: always

- url: /.*
  script: appengine_module.cr_rev.app.app
  secure: always

- url: /admin/.*
  script: appengine_module.cr_rev.app.app
  secure: always
  login: admin

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0
- name: numpy
  version: latest
