// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/qscheduler/qslib/protos/config.proto

package protos

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SchedulerConfig represents configuration information about the behavior of
// accounts for this quota scheduler pool.
type SchedulerConfig struct {
	// Configuration for a given account, keyed by account id.
	AccountConfigs map[string]*AccountConfig `protobuf:"bytes,1,rep,name=account_configs,json=accountConfigs,proto3" json:"account_configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// If set, scheduler will never preempt running tasks.
	DisablePreemption bool `protobuf:"varint,2,opt,name=disable_preemption,json=disablePreemption,proto3" json:"disable_preemption,omitempty"`
	// Labels is a list of swarming dimensions in "key:value" form. This corresponds
	// to swarming.ExternalSchedulerConfig.dimensionsions; it is the minimal set
	// of dimensions for tasks or bots that will use this scheduler.
	Labels               []string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchedulerConfig) Reset()         { *m = SchedulerConfig{} }
func (m *SchedulerConfig) String() string { return proto.CompactTextString(m) }
func (*SchedulerConfig) ProtoMessage()    {}
func (*SchedulerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_9585cdf0027c1e37, []int{0}
}

func (m *SchedulerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulerConfig.Unmarshal(m, b)
}
func (m *SchedulerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulerConfig.Marshal(b, m, deterministic)
}
func (m *SchedulerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulerConfig.Merge(m, src)
}
func (m *SchedulerConfig) XXX_Size() int {
	return xxx_messageInfo_SchedulerConfig.Size(m)
}
func (m *SchedulerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulerConfig proto.InternalMessageInfo

func (m *SchedulerConfig) GetAccountConfigs() map[string]*AccountConfig {
	if m != nil {
		return m.AccountConfigs
	}
	return nil
}

func (m *SchedulerConfig) GetDisablePreemption() bool {
	if m != nil {
		return m.DisablePreemption
	}
	return false
}

func (m *SchedulerConfig) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

// AccountConfig represents per-quota-account configuration information, such
// as the recharge parameters. This does not represent anything about the
// current state of an account.
type AccountConfig struct {
	// ChargeRate is the rates (per second) at which per-priority accounts grow.
	//
	// Conceptually this is the time-averaged number of workers that this account
	// may use, at each priority level.
	ChargeRate []float32 `protobuf:"fixed32,1,rep,packed,name=charge_rate,json=chargeRate,proto3" json:"charge_rate,omitempty"`
	// MaxChargeSeconds is the maximum amount of time over which this account can
	// accumulate quota before hitting its cap.
	//
	// Conceptually this sets the time window over which the time averaged
	// utilization by this account is measured. Very bursty clients will need to
	// use a wider window, whereas very consistent clients will use a narrow one.
	MaxChargeSeconds float32 `protobuf:"fixed32,2,opt,name=max_charge_seconds,json=maxChargeSeconds,proto3" json:"max_charge_seconds,omitempty"`
	// MaxFanout is the maximum number of concurrent paid jobs that this account
	// will pay for (0 = no limit).
	//
	// Additional jobs beyond this may run if there is idle capacity, but they
	// will run in the FreeBucket priority level.
	MaxFanout            int32    `protobuf:"varint,3,opt,name=max_fanout,json=maxFanout,proto3" json:"max_fanout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountConfig) Reset()         { *m = AccountConfig{} }
func (m *AccountConfig) String() string { return proto.CompactTextString(m) }
func (*AccountConfig) ProtoMessage()    {}
func (*AccountConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_9585cdf0027c1e37, []int{1}
}

func (m *AccountConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountConfig.Unmarshal(m, b)
}
func (m *AccountConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountConfig.Marshal(b, m, deterministic)
}
func (m *AccountConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountConfig.Merge(m, src)
}
func (m *AccountConfig) XXX_Size() int {
	return xxx_messageInfo_AccountConfig.Size(m)
}
func (m *AccountConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AccountConfig proto.InternalMessageInfo

func (m *AccountConfig) GetChargeRate() []float32 {
	if m != nil {
		return m.ChargeRate
	}
	return nil
}

func (m *AccountConfig) GetMaxChargeSeconds() float32 {
	if m != nil {
		return m.MaxChargeSeconds
	}
	return 0
}

func (m *AccountConfig) GetMaxFanout() int32 {
	if m != nil {
		return m.MaxFanout
	}
	return 0
}

func init() {
	proto.RegisterType((*SchedulerConfig)(nil), "protos.SchedulerConfig")
	proto.RegisterMapType((map[string]*AccountConfig)(nil), "protos.SchedulerConfig.AccountConfigsEntry")
	proto.RegisterType((*AccountConfig)(nil), "protos.AccountConfig")
}

func init() {
	proto.RegisterFile("infra/qscheduler/qslib/protos/config.proto", fileDescriptor_9585cdf0027c1e37)
}

var fileDescriptor_9585cdf0027c1e37 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x69, 0xcb, 0x86, 0xfb, 0x86, 0x6e, 0x46, 0x94, 0x22, 0x88, 0x65, 0xa7, 0xe2, 0x74,
	0x85, 0x79, 0x11, 0x6f, 0x32, 0xf4, 0x2c, 0x99, 0x07, 0x6f, 0xe5, 0x6b, 0xf7, 0x6d, 0x2b, 0xb6,
	0xc9, 0x96, 0xa4, 0xb2, 0x1d, 0xbc, 0xfb, 0x67, 0xcb, 0x92, 0x4d, 0xa8, 0x78, 0xcb, 0x7b, 0xef,
	0xf7, 0x78, 0x21, 0x81, 0x9b, 0x42, 0xcc, 0x15, 0x26, 0x6b, 0x9d, 0x2f, 0x69, 0x56, 0x97, 0xa4,
	0x92, 0xb5, 0x2e, 0x8b, 0x2c, 0x59, 0x29, 0x69, 0xa4, 0x4e, 0x72, 0x29, 0xe6, 0xc5, 0x62, 0x64,
	0x15, 0x6b, 0x3b, 0x73, 0xf0, 0xed, 0x43, 0x6f, 0x7a, 0xe0, 0x27, 0x96, 0x60, 0x6f, 0xd0, 0xc3,
	0x3c, 0x97, 0xb5, 0x30, 0xa9, 0xeb, 0xe8, 0xd0, 0x8b, 0x82, 0xb8, 0x3b, 0x1e, 0xba, 0xb2, 0x1e,
	0xfd, 0x69, 0x8c, 0x9e, 0x1c, 0xee, 0x94, 0x7e, 0x16, 0x46, 0x6d, 0xf9, 0x09, 0x36, 0x4c, 0x76,
	0x07, 0x6c, 0x56, 0x68, 0xcc, 0x4a, 0x4a, 0x57, 0x8a, 0xa8, 0x5a, 0x99, 0x42, 0x8a, 0xd0, 0x8f,
	0xbc, 0xf8, 0x88, 0x9f, 0xee, 0x93, 0xd7, 0xdf, 0x80, 0x5d, 0x40, 0xbb, 0xc4, 0x8c, 0x4a, 0x1d,
	0x06, 0x51, 0x10, 0x77, 0xf8, 0x5e, 0x5d, 0xbe, 0xc3, 0xd9, 0x3f, 0x6b, 0xac, 0x0f, 0xc1, 0x07,
	0x6d, 0x43, 0x2f, 0xf2, 0xe2, 0x0e, 0xdf, 0x1d, 0xd9, 0x10, 0x5a, 0x9f, 0x58, 0xd6, 0x64, 0x27,
	0xba, 0xe3, 0xf3, 0xc3, 0xdd, 0x1b, 0x6d, 0xee, 0x98, 0x47, 0xff, 0xc1, 0x1b, 0x7c, 0xc1, 0x71,
	0x23, 0x63, 0xd7, 0xd0, 0xcd, 0x97, 0xa8, 0x16, 0x94, 0x2a, 0x34, 0x64, 0xdf, 0xc0, 0xe7, 0xe0,
	0x2c, 0x8e, 0x86, 0xd8, 0x2d, 0xb0, 0x0a, 0x37, 0xe9, 0x1e, 0xd2, 0x94, 0x4b, 0x31, 0xd3, 0x76,
	0xcf, 0xe7, 0xfd, 0x0a, 0x37, 0x13, 0x1b, 0x4c, 0x9d, 0xcf, 0xae, 0x00, 0x76, 0xf4, 0x1c, 0x85,
	0xac, 0x4d, 0x18, 0x44, 0x5e, 0xdc, 0xe2, 0x9d, 0x0a, 0x37, 0x2f, 0xd6, 0xc8, 0xdc, 0x8f, 0xdc,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x36, 0xf8, 0xec, 0x94, 0xc6, 0x01, 0x00, 0x00,
}
