// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connection.proto

package inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NEXT TAG: 4
type ServoHostConnection struct {
	ServoHostId          *string  `protobuf:"bytes,1,req,name=servo_host_id,json=servoHostId" json:"servo_host_id,omitempty"`
	DutId                *string  `protobuf:"bytes,2,req,name=dut_id,json=dutId" json:"dut_id,omitempty"`
	ServoPort            *int32   `protobuf:"varint,3,req,name=servo_port,json=servoPort" json:"servo_port,omitempty"`
	ServoSerial          *string  `protobuf:"bytes,4,opt,name=servo_serial,json=servoSerial" json:"servo_serial,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServoHostConnection) Reset()         { *m = ServoHostConnection{} }
func (m *ServoHostConnection) String() string { return proto.CompactTextString(m) }
func (*ServoHostConnection) ProtoMessage()    {}
func (*ServoHostConnection) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{0}
}

func (m *ServoHostConnection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServoHostConnection.Unmarshal(m, b)
}
func (m *ServoHostConnection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServoHostConnection.Marshal(b, m, deterministic)
}
func (m *ServoHostConnection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServoHostConnection.Merge(m, src)
}
func (m *ServoHostConnection) XXX_Size() int {
	return xxx_messageInfo_ServoHostConnection.Size(m)
}
func (m *ServoHostConnection) XXX_DiscardUnknown() {
	xxx_messageInfo_ServoHostConnection.DiscardUnknown(m)
}

var xxx_messageInfo_ServoHostConnection proto.InternalMessageInfo

func (m *ServoHostConnection) GetServoHostId() string {
	if m != nil && m.ServoHostId != nil {
		return *m.ServoHostId
	}
	return ""
}

func (m *ServoHostConnection) GetDutId() string {
	if m != nil && m.DutId != nil {
		return *m.DutId
	}
	return ""
}

func (m *ServoHostConnection) GetServoPort() int32 {
	if m != nil && m.ServoPort != nil {
		return *m.ServoPort
	}
	return 0
}

func (m *ServoHostConnection) GetServoSerial() string {
	if m != nil && m.ServoSerial != nil {
		return *m.ServoSerial
	}
	return ""
}

// NEXT TAG: 3
type ChameleonConnection struct {
	Chameleon            *ChameleonDevice `protobuf:"bytes,1,req,name=chameleon" json:"chameleon,omitempty"`
	ControlledDevice     *Device          `protobuf:"bytes,2,req,name=controlled_device,json=controlledDevice" json:"controlled_device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ChameleonConnection) Reset()         { *m = ChameleonConnection{} }
func (m *ChameleonConnection) String() string { return proto.CompactTextString(m) }
func (*ChameleonConnection) ProtoMessage()    {}
func (*ChameleonConnection) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1}
}

func (m *ChameleonConnection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChameleonConnection.Unmarshal(m, b)
}
func (m *ChameleonConnection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChameleonConnection.Marshal(b, m, deterministic)
}
func (m *ChameleonConnection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChameleonConnection.Merge(m, src)
}
func (m *ChameleonConnection) XXX_Size() int {
	return xxx_messageInfo_ChameleonConnection.Size(m)
}
func (m *ChameleonConnection) XXX_DiscardUnknown() {
	xxx_messageInfo_ChameleonConnection.DiscardUnknown(m)
}

var xxx_messageInfo_ChameleonConnection proto.InternalMessageInfo

func (m *ChameleonConnection) GetChameleon() *ChameleonDevice {
	if m != nil {
		return m.Chameleon
	}
	return nil
}

func (m *ChameleonConnection) GetControlledDevice() *Device {
	if m != nil {
		return m.ControlledDevice
	}
	return nil
}

func init() {
	proto.RegisterType((*ServoHostConnection)(nil), "chrome.chromeos_infra.skylab.proto.inventory.ServoHostConnection")
	proto.RegisterType((*ChameleonConnection)(nil), "chrome.chromeos_infra.skylab.proto.inventory.ChameleonConnection")
}

func init() { proto.RegisterFile("connection.proto", fileDescriptor_51baa40a1cc6b48b) }

var fileDescriptor_51baa40a1cc6b48b = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x69, 0x75, 0x42, 0x5f, 0x27, 0xcc, 0x0e, 0xa1, 0x08, 0x42, 0xed, 0x69, 0x07, 0xc9,
	0x61, 0x78, 0xf5, 0xe2, 0x3c, 0xe8, 0x4d, 0xba, 0x9b, 0x1e, 0x4a, 0x4c, 0x9e, 0x34, 0x98, 0xe5,
	0x8d, 0x24, 0x2b, 0xec, 0x6b, 0xf8, 0xdd, 0xfc, 0x3e, 0xb2, 0xc4, 0x75, 0xbb, 0xee, 0x54, 0xf8,
	0xfd, 0xff, 0xfd, 0xe5, 0xbd, 0x07, 0x13, 0x41, 0xc6, 0xa0, 0xf0, 0x8a, 0x0c, 0x5b, 0x5b, 0xf2,
	0x54, 0xdc, 0x8b, 0xce, 0xd2, 0x0a, 0x59, 0xfc, 0x90, 0x6b, 0x95, 0xf9, 0xb2, 0x9c, 0xb9, 0xef,
	0xad, 0xe6, 0x9f, 0xb1, 0xc3, 0x94, 0xe9, 0xd1, 0x78, 0xb2, 0xdb, 0x9b, 0xb1, 0xc4, 0x5e, 0x09,
	0x8c, 0xbc, 0xfe, 0x49, 0x60, 0xba, 0x44, 0xdb, 0xd3, 0x0b, 0x39, 0xbf, 0x18, 0xcc, 0x45, 0x0d,
	0x97, 0x6e, 0x87, 0xdb, 0x8e, 0x9c, 0x6f, 0x95, 0x2c, 0x93, 0x2a, 0x9d, 0x65, 0x4d, 0xee, 0xf6,
	0xdd, 0x57, 0x59, 0x5c, 0xc3, 0x85, 0xdc, 0x84, 0x30, 0x0d, 0xe1, 0x48, 0x6e, 0x76, 0xf8, 0x16,
	0x20, 0xfe, 0xba, 0x26, 0xeb, 0xcb, 0xb3, 0x2a, 0x9d, 0x8d, 0x9a, 0x2c, 0x90, 0x37, 0xb2, 0xbe,
	0xb8, 0x83, 0x71, 0x8c, 0x1d, 0x5a, 0xc5, 0x75, 0x79, 0x5e, 0x25, 0x83, 0x78, 0x19, 0x50, 0xfd,
	0x9b, 0xc0, 0x74, 0xd1, 0xf1, 0x15, 0x6a, 0x24, 0x73, 0x34, 0xd4, 0x07, 0x64, 0x62, 0x8f, 0xc3,
	0x40, 0xf9, 0xfc, 0x91, 0x9d, 0xb2, 0x3c, 0x1b, 0xac, 0xcf, 0xe1, 0x08, 0xcd, 0xc1, 0x57, 0x70,
	0xb8, 0x12, 0x64, 0xbc, 0x25, 0xad, 0x51, 0xb6, 0xf1, 0x48, 0x61, 0xb1, 0x7c, 0xfe, 0x70, 0xda,
	0x23, 0xff, 0xee, 0xc9, 0x41, 0x17, 0xc9, 0x53, 0xfe, 0x9e, 0x0d, 0xad, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe4, 0x5b, 0x15, 0x53, 0xc8, 0x01, 0x00, 0x00,
}
