// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/qscheduler/qslib/types/types.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import account "infra/qscheduler/qslib/types/account"
import task "infra/qscheduler/qslib/types/task"
import vector "infra/qscheduler/qslib/types/vector"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Worker represents a resource that can run 1 task at a time. This corresponds
// to the swarming concept of a Bot. This representation considers only the
// subset of Labels that are Provisionable (can be changed by running a task),
// because the quota scheduler algorithm is expected to run against a pool of
// otherwise homogenous workers.
type Worker struct {
	// Labels represents the set of provisionable labels that this worker
	// possesses.
	Labels []string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	// RunningTask is, if non-nil, the task that is currently running on the
	// worker.
	RunningTask          *task.Run `protobuf:"bytes,2,opt,name=running_task,json=runningTask,proto3" json:"running_task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Worker) Reset()         { *m = Worker{} }
func (m *Worker) String() string { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()    {}
func (*Worker) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_16b28f7bfea33761, []int{0}
}
func (m *Worker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Worker.Unmarshal(m, b)
}
func (m *Worker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Worker.Marshal(b, m, deterministic)
}
func (dst *Worker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Worker.Merge(dst, src)
}
func (m *Worker) XXX_Size() int {
	return xxx_messageInfo_Worker.Size(m)
}
func (m *Worker) XXX_DiscardUnknown() {
	xxx_messageInfo_Worker.DiscardUnknown(m)
}

var xxx_messageInfo_Worker proto.InternalMessageInfo

func (m *Worker) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Worker) GetRunningTask() *task.Run {
	if m != nil {
		return m.RunningTask
	}
	return nil
}

// State represents the overall state of a quota scheduler worker pool,
// account set, and task queue. This is represented separately from
// configuration information. The state is expected to be updated frequently,
// on each scheduler tick.
type State struct {
	// Requests that are waiting to be assigned to a worker, keyed by
	// request id.
	Requests map[string]*task.Request `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Balance of all quota accounts for this pool, keyed by account id.
	Balances map[string]*vector.Vector `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Workers that may run tasks, and their states, keyed by worker id.
	Workers map[string]*Worker `protobuf:"bytes,3,rep,name=workers,proto3" json:"workers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// LastAccountUpdate is the last time at which quota account balances
	// were updated.
	LastAccountUpdate    *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_account_update,json=lastAccountUpdate,proto3" json:"last_account_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_16b28f7bfea33761, []int{1}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetRequests() map[string]*task.Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *State) GetBalances() map[string]*vector.Vector {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *State) GetWorkers() map[string]*Worker {
	if m != nil {
		return m.Workers
	}
	return nil
}

func (m *State) GetLastAccountUpdate() *timestamp.Timestamp {
	if m != nil {
		return m.LastAccountUpdate
	}
	return nil
}

// Config represents configuration information about the behavior of accounts
// for this quota scheduler pool.
type Config struct {
	// Configuration for a given account, keyed by account id.
	AccountConfigs       map[string]*account.Config `protobuf:"bytes,1,rep,name=account_configs,json=accountConfigs,proto3" json:"account_configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_16b28f7bfea33761, []int{2}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAccountConfigs() map[string]*account.Config {
	if m != nil {
		return m.AccountConfigs
	}
	return nil
}

func init() {
	proto.RegisterType((*Worker)(nil), "types.Worker")
	proto.RegisterType((*State)(nil), "types.State")
	proto.RegisterMapType((map[string]*vector.Vector)(nil), "types.State.BalancesEntry")
	proto.RegisterMapType((map[string]*task.Request)(nil), "types.State.RequestsEntry")
	proto.RegisterMapType((map[string]*Worker)(nil), "types.State.WorkersEntry")
	proto.RegisterType((*Config)(nil), "types.Config")
	proto.RegisterMapType((map[string]*account.Config)(nil), "types.Config.AccountConfigsEntry")
}

func init() {
	proto.RegisterFile("infra/qscheduler/qslib/types/types.proto", fileDescriptor_types_16b28f7bfea33761)
}

var fileDescriptor_types_16b28f7bfea33761 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x95, 0x96, 0x16, 0x3a, 0xdd, 0xee, 0x82, 0x57, 0x42, 0x21, 0x17, 0x4a, 0x01, 0xa9,
	0x87, 0x95, 0x83, 0xba, 0x12, 0x42, 0xdc, 0x00, 0x71, 0xa0, 0x48, 0x1c, 0xcc, 0x02, 0xc7, 0xca,
	0xc9, 0xba, 0x25, 0x6a, 0xd6, 0x6e, 0xfd, 0xa7, 0xa8, 0x6f, 0xc4, 0x43, 0xf1, 0x30, 0xa8, 0xf6,
	0x18, 0x35, 0x52, 0x54, 0x71, 0x89, 0xe3, 0x99, 0xef, 0x37, 0x9a, 0xf9, 0xc6, 0x30, 0xad, 0xe4,
	0x52, 0xf3, 0x7c, 0x6b, 0xca, 0x9f, 0xe2, 0xd6, 0xd5, 0x42, 0xe7, 0x5b, 0x53, 0x57, 0x45, 0x6e,
	0xf7, 0x1b, 0x61, 0xc2, 0x97, 0x6e, 0xb4, 0xb2, 0x8a, 0xf4, 0xfc, 0x25, 0x7b, 0xba, 0x52, 0x6a,
	0x55, 0x8b, 0xdc, 0x07, 0x0b, 0xb7, 0xcc, 0x6d, 0x75, 0x27, 0x8c, 0xe5, 0x77, 0x9b, 0xa0, 0xcb,
	0xae, 0x4e, 0x57, 0xe4, 0x66, 0xed, 0x3f, 0xa8, 0x7e, 0x75, 0x52, 0xbd, 0x13, 0xa5, 0x55, 0x1a,
	0x0f, 0x24, 0x66, 0x27, 0x09, 0x5e, 0x96, 0xca, 0x49, 0x1b, 0xcf, 0xc0, 0x4c, 0xbe, 0x40, 0xff,
	0x87, 0xd2, 0x6b, 0xa1, 0xc9, 0x63, 0xe8, 0xd7, 0xbc, 0x10, 0xb5, 0x49, 0x93, 0x71, 0x77, 0x3a,
	0x60, 0x78, 0x23, 0x57, 0x70, 0xa6, 0x9d, 0x94, 0x95, 0x5c, 0x2d, 0x0e, 0xdd, 0xa5, 0x9d, 0x71,
	0x32, 0x1d, 0xce, 0x06, 0xd4, 0xb7, 0xca, 0x9c, 0x64, 0x43, 0x4c, 0xdf, 0x70, 0xb3, 0x9e, 0xfc,
	0xe9, 0x42, 0xef, 0xab, 0xe5, 0x56, 0x90, 0xd7, 0xf0, 0x40, 0x8b, 0xad, 0x13, 0xc6, 0x86, 0x8a,
	0xc3, 0x59, 0x46, 0x83, 0x6b, 0x3e, 0x4f, 0x19, 0x26, 0x3f, 0x4a, 0xab, 0xf7, 0xec, 0x9f, 0xf6,
	0xc0, 0x15, 0xbc, 0xe6, 0xb2, 0x14, 0x26, 0xed, 0xb4, 0x70, 0xef, 0x31, 0x89, 0x5c, 0xd4, 0x92,
	0x6b, 0xb8, 0xff, 0xcb, 0x4f, 0x62, 0xd2, 0xae, 0xc7, 0x9e, 0x34, 0xb0, 0x30, 0x25, 0x52, 0x51,
	0x49, 0xe6, 0x70, 0x59, 0x73, 0x63, 0x17, 0x68, 0xca, 0xc2, 0x6d, 0x6e, 0xb9, 0x15, 0xe9, 0x3d,
	0x3f, 0x63, 0x46, 0xc3, 0x46, 0x69, 0xdc, 0x28, 0xbd, 0x89, 0x1b, 0x65, 0x8f, 0x0e, 0xd8, 0xbb,
	0x40, 0x7d, 0xf3, 0x50, 0x36, 0x87, 0x51, 0x63, 0x26, 0xf2, 0x10, 0xba, 0x6b, 0xb1, 0x4f, 0x93,
	0x71, 0x32, 0x1d, 0xb0, 0xc3, 0x2f, 0x79, 0x0e, 0xbd, 0x1d, 0xaf, 0x9d, 0x40, 0x13, 0x47, 0x68,
	0x62, 0xa0, 0x58, 0xc8, 0xbd, 0xed, 0xbc, 0x49, 0xb2, 0xcf, 0x30, 0x6a, 0xcc, 0xd9, 0x52, 0xeb,
	0x45, 0xb3, 0xd6, 0x39, 0xc5, 0xb7, 0xf0, 0xdd, 0x1f, 0xc7, 0xc5, 0x3e, 0xc1, 0xd9, 0xf1, 0xf4,
	0xff, 0xd5, 0x97, 0x77, 0x2e, 0x50, 0x47, 0xa5, 0x26, 0xbf, 0x13, 0xe8, 0x7f, 0x50, 0x72, 0x59,
	0xad, 0xc8, 0x1c, 0x2e, 0xa2, 0x6b, 0xa5, 0x8f, 0xc4, 0x35, 0x3f, 0x43, 0x3a, 0xe8, 0x28, 0x9a,
	0x14, 0x6e, 0xe8, 0xff, 0x39, 0x6f, 0x04, 0x33, 0x06, 0x97, 0x2d, 0xb2, 0x96, 0x46, 0x5f, 0x36,
	0x1b, 0xbd, 0xa0, 0xf1, 0x35, 0x07, 0xee, 0xa8, 0xd5, 0xa2, 0xef, 0xb7, 0x76, 0xfd, 0x37, 0x00,
	0x00, 0xff, 0xff, 0x41, 0xaf, 0x44, 0xf5, 0xc8, 0x03, 0x00, 0x00,
}
