// Code generated by protoc-gen-go. DO NOT EDIT.
// source: infra/appengine/crosskylabadmin/app/config/config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config is the configuration data served by luci-config for this app.
type Config struct {
	// AccessGroup is the luci-auth group controlling access to admin app APIs.
	AccessGroup string `protobuf:"bytes,1,opt,name=access_group,json=accessGroup,proto3" json:"access_group,omitempty"`
	// Swarming contains information about the Swarming instance that hosts the
	// bots managed by this app.
	Swarming *Swarming `protobuf:"bytes,2,opt,name=swarming,proto3" json:"swarming,omitempty"`
	// Tasker contains configuration data specific to the Tasker API endpoints.
	Tasker *Tasker `protobuf:"bytes,3,opt,name=tasker,proto3" json:"tasker,omitempty"`
	// Cron contains the configuration data specific to cron jobs on this app.
	Cron *Cron `protobuf:"bytes,4,opt,name=cron,proto3" json:"cron,omitempty"`
	// Inventory contains configuration information about skylab inventory
	// repo.
	Inventory            *Inventory `protobuf:"bytes,5,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85dab011e4afc14, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAccessGroup() string {
	if m != nil {
		return m.AccessGroup
	}
	return ""
}

func (m *Config) GetSwarming() *Swarming {
	if m != nil {
		return m.Swarming
	}
	return nil
}

func (m *Config) GetTasker() *Tasker {
	if m != nil {
		return m.Tasker
	}
	return nil
}

func (m *Config) GetCron() *Cron {
	if m != nil {
		return m.Cron
	}
	return nil
}

func (m *Config) GetInventory() *Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

// Swarming contains information about the Swarming instance that hosts the bots
// managed by this app.
type Swarming struct {
	// Host is the swarming instance hosting skylab bots.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// BotPool is the swarming pool containing skylab bots.
	BotPool string `protobuf:"bytes,2,opt,name=bot_pool,json=botPool,proto3" json:"bot_pool,omitempty"`
	// FleetAdminTaskTag identifies all tasks created by the fleet admin app.
	FleetAdminTaskTag string `protobuf:"bytes,3,opt,name=fleet_admin_task_tag,json=fleetAdminTaskTag,proto3" json:"fleet_admin_task_tag,omitempty"`
	// LuciProjectTag is the swarming tag that associates the task with a
	// luci project, allowing milo to work with the swarming UI.
	LuciProjectTag       string   `protobuf:"bytes,4,opt,name=luci_project_tag,json=luciProjectTag,proto3" json:"luci_project_tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Swarming) Reset()         { *m = Swarming{} }
func (m *Swarming) String() string { return proto.CompactTextString(m) }
func (*Swarming) ProtoMessage()    {}
func (*Swarming) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85dab011e4afc14, []int{1}
}

func (m *Swarming) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Swarming.Unmarshal(m, b)
}
func (m *Swarming) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Swarming.Marshal(b, m, deterministic)
}
func (m *Swarming) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Swarming.Merge(m, src)
}
func (m *Swarming) XXX_Size() int {
	return xxx_messageInfo_Swarming.Size(m)
}
func (m *Swarming) XXX_DiscardUnknown() {
	xxx_messageInfo_Swarming.DiscardUnknown(m)
}

var xxx_messageInfo_Swarming proto.InternalMessageInfo

func (m *Swarming) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Swarming) GetBotPool() string {
	if m != nil {
		return m.BotPool
	}
	return ""
}

func (m *Swarming) GetFleetAdminTaskTag() string {
	if m != nil {
		return m.FleetAdminTaskTag
	}
	return ""
}

func (m *Swarming) GetLuciProjectTag() string {
	if m != nil {
		return m.LuciProjectTag
	}
	return ""
}

// Tasker contains configuration data specific to the Tasker API endpoints.
type Tasker struct {
	// BackgroundTaskExecutionTimeoutSecs is the execution timeout (in
	// seconds) for background tasks created by tasker.
	BackgroundTaskExecutionTimeoutSecs int64 `protobuf:"varint,1,opt,name=background_task_execution_timeout_secs,json=backgroundTaskExecutionTimeoutSecs,proto3" json:"background_task_execution_timeout_secs,omitempty"`
	// BackgroundTaskExpirationSecs is the expiration time (in seconds) for
	// background tasks created by tasker.
	BackgroundTaskExpirationSecs int64 `protobuf:"varint,2,opt,name=background_task_expiration_secs,json=backgroundTaskExpirationSecs,proto3" json:"background_task_expiration_secs,omitempty"`
	// LogdogHost is the Logdog host to use for logging from the created tasks.
	LogdogHost string `protobuf:"bytes,3,opt,name=logdog_host,json=logdogHost,proto3" json:"logdog_host,omitempty"`
	// AdminTaskUser is the name of the service account to use for admin
	// tasks.
	AdminTaskUser        string   `protobuf:"bytes,4,opt,name=admin_task_user,json=adminTaskUser,proto3" json:"admin_task_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tasker) Reset()         { *m = Tasker{} }
func (m *Tasker) String() string { return proto.CompactTextString(m) }
func (*Tasker) ProtoMessage()    {}
func (*Tasker) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85dab011e4afc14, []int{2}
}

func (m *Tasker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tasker.Unmarshal(m, b)
}
func (m *Tasker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tasker.Marshal(b, m, deterministic)
}
func (m *Tasker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tasker.Merge(m, src)
}
func (m *Tasker) XXX_Size() int {
	return xxx_messageInfo_Tasker.Size(m)
}
func (m *Tasker) XXX_DiscardUnknown() {
	xxx_messageInfo_Tasker.DiscardUnknown(m)
}

var xxx_messageInfo_Tasker proto.InternalMessageInfo

func (m *Tasker) GetBackgroundTaskExecutionTimeoutSecs() int64 {
	if m != nil {
		return m.BackgroundTaskExecutionTimeoutSecs
	}
	return 0
}

func (m *Tasker) GetBackgroundTaskExpirationSecs() int64 {
	if m != nil {
		return m.BackgroundTaskExpirationSecs
	}
	return 0
}

func (m *Tasker) GetLogdogHost() string {
	if m != nil {
		return m.LogdogHost
	}
	return ""
}

func (m *Tasker) GetAdminTaskUser() string {
	if m != nil {
		return m.AdminTaskUser
	}
	return ""
}

// Cron contains the configuration data specific to cron jobs on this app.
type Cron struct {
	// FleetAdminTaskPriority is the swarming task priority of created tasks.
	//
	// This must be numerically smaller (i.e. more important) than Skylab's test
	// task priority range [49-255] and numerically larger than the minimum
	// allowed Swarming priority (20) for non administrator users.
	FleetAdminTaskPriority int64 `protobuf:"varint,1,opt,name=fleet_admin_task_priority,json=fleetAdminTaskPriority,proto3" json:"fleet_admin_task_priority,omitempty"`
	// EnsureTasksCount is the number of background tasks maintained against
	// each bot.
	EnsureTasksCount int32 `protobuf:"varint,2,opt,name=ensure_tasks_count,json=ensureTasksCount,proto3" json:"ensure_tasks_count,omitempty"`
	// RepairIdleDuration is the duration for which a bot in the fleet must have
	// been idle for a repair task to be created against it.
	RepairIdleDuration *duration.Duration `protobuf:"bytes,3,opt,name=repair_idle_duration,json=repairIdleDuration,proto3" json:"repair_idle_duration,omitempty"`
	// RepairAttemptDelayDuration is the time between successive attempts at
	// repairing repair failed bots in the fleet.
	RepairAttemptDelayDuration *duration.Duration `protobuf:"bytes,4,opt,name=repair_attempt_delay_duration,json=repairAttemptDelayDuration,proto3" json:"repair_attempt_delay_duration,omitempty"`
	// Configuration of automatic pool balancing to keep critical pools healthy.
	PoolBalancer         *PoolBalancer `protobuf:"bytes,5,opt,name=pool_balancer,json=poolBalancer,proto3" json:"pool_balancer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Cron) Reset()         { *m = Cron{} }
func (m *Cron) String() string { return proto.CompactTextString(m) }
func (*Cron) ProtoMessage()    {}
func (*Cron) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85dab011e4afc14, []int{3}
}

func (m *Cron) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cron.Unmarshal(m, b)
}
func (m *Cron) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cron.Marshal(b, m, deterministic)
}
func (m *Cron) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cron.Merge(m, src)
}
func (m *Cron) XXX_Size() int {
	return xxx_messageInfo_Cron.Size(m)
}
func (m *Cron) XXX_DiscardUnknown() {
	xxx_messageInfo_Cron.DiscardUnknown(m)
}

var xxx_messageInfo_Cron proto.InternalMessageInfo

func (m *Cron) GetFleetAdminTaskPriority() int64 {
	if m != nil {
		return m.FleetAdminTaskPriority
	}
	return 0
}

func (m *Cron) GetEnsureTasksCount() int32 {
	if m != nil {
		return m.EnsureTasksCount
	}
	return 0
}

func (m *Cron) GetRepairIdleDuration() *duration.Duration {
	if m != nil {
		return m.RepairIdleDuration
	}
	return nil
}

func (m *Cron) GetRepairAttemptDelayDuration() *duration.Duration {
	if m != nil {
		return m.RepairAttemptDelayDuration
	}
	return nil
}

func (m *Cron) GetPoolBalancer() *PoolBalancer {
	if m != nil {
		return m.PoolBalancer
	}
	return nil
}

// Skylab inventory is stored in a git project. A Gitiles server as well as
// Gerrit review server are used by this app to view and update the inventory
// data.
type Inventory struct {
	// Gitiles server hosting inventory project.
	// e.g. chromium.googlesource.com
	GitilesHost string `protobuf:"bytes,1,opt,name=gitiles_host,json=gitilesHost,proto3" json:"gitiles_host,omitempty"`
	// Gerrit code review server hosting inventory project.
	// e.g. chromium-review.googlesource.com
	GerritHost string `protobuf:"bytes,2,opt,name=gerrit_host,json=gerritHost,proto3" json:"gerrit_host,omitempty"`
	// Git project containing the inventory data.
	Project string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	// Git branch from the inventory project to be used.
	Branch   string `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	DataPath string `protobuf:"bytes,5,opt,name=data_path,json=dataPath,proto3" json:"data_path,omitempty"` // Deprecated: Do not use.
	// Inventory environment managed by this instance of the app.
	// e.g. ENVIRONMENT_STAGING
	Environment string `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	// Path to the infrastructure inventory data file within the git project.
	// e.g. data/skylab/server_db.textpb
	InfrastructureDataPath string `protobuf:"bytes,7,opt,name=infrastructure_data_path,json=infrastructureDataPath,proto3" json:"infrastructure_data_path,omitempty"`
	// Path to the lab inventory data file within the git project.
	// e.g. data/skylab/lab.textpb
	LabDataPath          string   `protobuf:"bytes,8,opt,name=lab_data_path,json=labDataPath,proto3" json:"lab_data_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inventory) Reset()         { *m = Inventory{} }
func (m *Inventory) String() string { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()    {}
func (*Inventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85dab011e4afc14, []int{4}
}

func (m *Inventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory.Unmarshal(m, b)
}
func (m *Inventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory.Marshal(b, m, deterministic)
}
func (m *Inventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory.Merge(m, src)
}
func (m *Inventory) XXX_Size() int {
	return xxx_messageInfo_Inventory.Size(m)
}
func (m *Inventory) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory proto.InternalMessageInfo

func (m *Inventory) GetGitilesHost() string {
	if m != nil {
		return m.GitilesHost
	}
	return ""
}

func (m *Inventory) GetGerritHost() string {
	if m != nil {
		return m.GerritHost
	}
	return ""
}

func (m *Inventory) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Inventory) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

// Deprecated: Do not use.
func (m *Inventory) GetDataPath() string {
	if m != nil {
		return m.DataPath
	}
	return ""
}

func (m *Inventory) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *Inventory) GetInfrastructureDataPath() string {
	if m != nil {
		return m.InfrastructureDataPath
	}
	return ""
}

func (m *Inventory) GetLabDataPath() string {
	if m != nil {
		return m.LabDataPath
	}
	return ""
}

type PoolBalancer struct {
	// Names of the pools to keep healthy automatically via pool balancing.
	TargetPools []string `protobuf:"bytes,1,rep,name=target_pools,json=targetPools,proto3" json:"target_pools,omitempty"`
	// Name of the pool to use as the spare pool for pool balancing.
	SparePool string `protobuf:"bytes,2,opt,name=spare_pool,json=sparePool,proto3" json:"spare_pool,omitempty"`
	// Maximum number of unhealthy DUTs per model that can be balanced away from
	// a single target pool.
	MaxUnhealthyDuts     int32    `protobuf:"varint,3,opt,name=max_unhealthy_duts,json=maxUnhealthyDuts,proto3" json:"max_unhealthy_duts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PoolBalancer) Reset()         { *m = PoolBalancer{} }
func (m *PoolBalancer) String() string { return proto.CompactTextString(m) }
func (*PoolBalancer) ProtoMessage()    {}
func (*PoolBalancer) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85dab011e4afc14, []int{5}
}

func (m *PoolBalancer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolBalancer.Unmarshal(m, b)
}
func (m *PoolBalancer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolBalancer.Marshal(b, m, deterministic)
}
func (m *PoolBalancer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolBalancer.Merge(m, src)
}
func (m *PoolBalancer) XXX_Size() int {
	return xxx_messageInfo_PoolBalancer.Size(m)
}
func (m *PoolBalancer) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolBalancer.DiscardUnknown(m)
}

var xxx_messageInfo_PoolBalancer proto.InternalMessageInfo

func (m *PoolBalancer) GetTargetPools() []string {
	if m != nil {
		return m.TargetPools
	}
	return nil
}

func (m *PoolBalancer) GetSparePool() string {
	if m != nil {
		return m.SparePool
	}
	return ""
}

func (m *PoolBalancer) GetMaxUnhealthyDuts() int32 {
	if m != nil {
		return m.MaxUnhealthyDuts
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "crosskylabadmin.config.Config")
	proto.RegisterType((*Swarming)(nil), "crosskylabadmin.config.Swarming")
	proto.RegisterType((*Tasker)(nil), "crosskylabadmin.config.Tasker")
	proto.RegisterType((*Cron)(nil), "crosskylabadmin.config.Cron")
	proto.RegisterType((*Inventory)(nil), "crosskylabadmin.config.Inventory")
	proto.RegisterType((*PoolBalancer)(nil), "crosskylabadmin.config.PoolBalancer")
}

func init() {
	proto.RegisterFile("infra/appengine/crosskylabadmin/app/config/config.proto", fileDescriptor_d85dab011e4afc14)
}

var fileDescriptor_d85dab011e4afc14 = []byte{
	// 785 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5f, 0x4f, 0xfb, 0x36,
	0x14, 0x55, 0x4b, 0x29, 0xcd, 0x2d, 0x6c, 0xcc, 0x42, 0x55, 0x40, 0x40, 0x4b, 0x34, 0x21, 0x1e,
	0x50, 0x3b, 0x6d, 0xd2, 0xfe, 0x48, 0x93, 0x26, 0xa0, 0x68, 0x43, 0x7b, 0xa9, 0x42, 0x79, 0x99,
	0x26, 0x59, 0x4e, 0xe2, 0xa6, 0x1e, 0xa9, 0x1d, 0xd9, 0x0e, 0xa3, 0x2f, 0xfb, 0x14, 0x7c, 0x82,
	0x7d, 0xb7, 0xbd, 0xed, 0x43, 0x4c, 0xfe, 0x13, 0x5a, 0x60, 0xd5, 0xef, 0xa9, 0xcd, 0xb9, 0xe7,
	0x9c, 0xe4, 0x9e, 0x7b, 0x6d, 0xf8, 0x8e, 0xf1, 0x99, 0x24, 0x23, 0x52, 0x96, 0x94, 0xe7, 0x8c,
	0xd3, 0x51, 0x2a, 0x85, 0x52, 0x8f, 0xcb, 0x82, 0x24, 0x24, 0x5b, 0x30, 0x6e, 0x2a, 0xa3, 0x54,
	0xf0, 0x19, 0xcb, 0xfd, 0xcf, 0xb0, 0x94, 0x42, 0x0b, 0xd4, 0x7b, 0x47, 0x1c, 0xba, 0xea, 0xd1,
	0x69, 0x2e, 0x44, 0x5e, 0xd0, 0x91, 0x65, 0x25, 0xd5, 0x6c, 0x94, 0x55, 0x92, 0x68, 0x26, 0xb8,
	0xd3, 0x45, 0x2f, 0x4d, 0x68, 0xdf, 0x58, 0x2a, 0x3a, 0x83, 0x5d, 0x92, 0xa6, 0x54, 0x29, 0x9c,
	0x4b, 0x51, 0x95, 0x61, 0x63, 0xd0, 0xb8, 0x08, 0xe2, 0xae, 0xc3, 0x7e, 0x36, 0x10, 0xfa, 0x11,
	0x3a, 0xea, 0x4f, 0x22, 0x17, 0x8c, 0xe7, 0x61, 0x73, 0xd0, 0xb8, 0xe8, 0x7e, 0x3d, 0x18, 0xfe,
	0xff, 0x8b, 0x87, 0xf7, 0x9e, 0x17, 0xbf, 0x2a, 0xd0, 0xb7, 0xd0, 0xd6, 0x44, 0x3d, 0x52, 0x19,
	0x6e, 0x59, 0xed, 0xe9, 0x26, 0xed, 0xd4, 0xb2, 0x62, 0xcf, 0x46, 0x5f, 0x41, 0x2b, 0x95, 0x82,
	0x87, 0x2d, 0xab, 0x3a, 0xde, 0xa4, 0xba, 0x91, 0x82, 0xc7, 0x96, 0x89, 0x7e, 0x82, 0x80, 0xf1,
	0x27, 0xca, 0xb5, 0x90, 0xcb, 0x70, 0xdb, 0xca, 0xce, 0x36, 0xc9, 0xee, 0x6a, 0x62, 0xbc, 0xd2,
	0x44, 0x2f, 0x0d, 0xe8, 0xd4, 0x1d, 0x20, 0x04, 0xad, 0xb9, 0x50, 0xda, 0x07, 0x62, 0xff, 0xa3,
	0x43, 0xe8, 0x24, 0x42, 0xe3, 0x52, 0x88, 0xc2, 0x26, 0x11, 0xc4, 0x3b, 0x89, 0xd0, 0x13, 0x21,
	0x0a, 0x34, 0x82, 0x83, 0x59, 0x41, 0xa9, 0xc6, 0xf6, 0x35, 0xd8, 0x34, 0x81, 0x35, 0xc9, 0x6d,
	0xd3, 0x41, 0xfc, 0x85, 0xad, 0x5d, 0x99, 0x92, 0x69, 0x73, 0x4a, 0x72, 0x74, 0x01, 0xfb, 0x45,
	0x95, 0x32, 0x5c, 0x4a, 0xf1, 0x07, 0x4d, 0xb5, 0x25, 0xb7, 0x2c, 0xf9, 0x33, 0x83, 0x4f, 0x1c,
	0x3c, 0x25, 0x79, 0xf4, 0x6f, 0x03, 0xda, 0x2e, 0x1c, 0x14, 0xc3, 0x79, 0x42, 0xd2, 0x47, 0x33,
	0x2a, 0x9e, 0xb9, 0x97, 0xd0, 0x67, 0x9a, 0x56, 0x66, 0xb6, 0x58, 0xb3, 0x05, 0x15, 0x95, 0xc6,
	0x8a, 0xa6, 0xca, 0x7e, 0xf6, 0x56, 0x1c, 0xad, 0xd8, 0xc6, 0xe1, 0xb6, 0xe6, 0x4e, 0x1d, 0xf5,
	0x9e, 0xa6, 0x0a, 0xdd, 0x42, 0xff, 0xa3, 0x67, 0xc9, 0xdc, 0xc2, 0x38, 0xb3, 0xa6, 0x35, 0x3b,
	0x7e, 0x6f, 0x56, 0x93, 0xac, 0x4d, 0x1f, 0xba, 0x85, 0xc8, 0x33, 0x91, 0x63, 0x1b, 0x9b, 0xeb,
	0x1b, 0x1c, 0xf4, 0x8b, 0x09, 0xef, 0x1c, 0x3e, 0x5f, 0xcb, 0xa6, 0x52, 0x54, 0xfa, 0x7e, 0xf7,
	0x48, 0x9d, 0xcb, 0x83, 0xa2, 0x32, 0xfa, 0xa7, 0x09, 0x2d, 0x33, 0x55, 0xf4, 0x03, 0x1c, 0x7e,
	0x88, 0xb4, 0x94, 0x4c, 0x48, 0xa6, 0x97, 0xbe, 0xbf, 0xde, 0xdb, 0x5c, 0x27, 0xbe, 0x8a, 0x2e,
	0x01, 0x51, 0xae, 0x2a, 0x49, 0xad, 0x4a, 0xe1, 0x54, 0x54, 0x5c, 0xdb, 0x36, 0xb6, 0xe3, 0x7d,
	0x57, 0x31, 0x7c, 0x75, 0x63, 0x70, 0xf4, 0x2b, 0x1c, 0x48, 0x5a, 0x12, 0x26, 0x31, 0xcb, 0x0a,
	0x8a, 0xeb, 0xc3, 0xe2, 0x17, 0xf6, 0x70, 0xe8, 0x4e, 0xd3, 0xb0, 0x3e, 0x4d, 0xc3, 0xb1, 0x27,
	0xc4, 0xc8, 0xc9, 0xee, 0xb2, 0x82, 0xd6, 0x18, 0xfa, 0x1d, 0x4e, 0xbc, 0x19, 0xd1, 0x9a, 0x2e,
	0x4a, 0x8d, 0x33, 0x5a, 0x90, 0xe5, 0xca, 0xb5, 0xf5, 0x29, 0xd7, 0x23, 0xa7, 0xbf, 0x72, 0xf2,
	0xb1, 0x51, 0xbf, 0xba, 0xdf, 0xc1, 0x9e, 0xd9, 0x3e, 0x9c, 0x90, 0x82, 0xf0, 0x94, 0x4a, 0xbf,
	0xe7, 0x5f, 0x6e, 0xda, 0x73, 0xb3, 0x9b, 0xd7, 0x9e, 0x1b, 0xef, 0x96, 0x6b, 0x4f, 0xd1, 0xdf,
	0x4d, 0x08, 0x5e, 0x8f, 0x81, 0xb9, 0x07, 0x72, 0xa6, 0x59, 0x41, 0x15, 0x5e, 0x5b, 0xfb, 0xae,
	0xc7, 0xec, 0x00, 0xfb, 0xd0, 0xcd, 0xa9, 0x94, 0x4c, 0x3b, 0x86, 0x3b, 0x00, 0xe0, 0x20, 0x4b,
	0x08, 0x61, 0xc7, 0x6f, 0xb3, 0x1f, 0x7f, 0xfd, 0x88, 0x7a, 0xd0, 0x4e, 0x24, 0xe1, 0xe9, 0xdc,
	0x8f, 0xdc, 0x3f, 0xa1, 0x3e, 0x04, 0x19, 0xd1, 0x04, 0x97, 0x44, 0xcf, 0x6d, 0x2b, 0xc1, 0x75,
	0x33, 0x6c, 0xc4, 0x1d, 0x03, 0x4e, 0x88, 0x9e, 0xa3, 0x01, 0x74, 0x29, 0x7f, 0x62, 0x52, 0xf0,
	0x05, 0xe5, 0x3a, 0x6c, 0xbb, 0xaf, 0x5a, 0x83, 0xd0, 0xf7, 0x10, 0xda, 0xeb, 0x53, 0x69, 0x59,
	0xa5, 0xda, 0x8c, 0x7c, 0xe5, 0xb8, 0x63, 0xe9, 0xbd, 0xb7, 0xf5, 0x71, 0xed, 0x1d, 0xc1, 0x5e,
	0x41, 0x92, 0x35, 0x7a, 0xc7, 0xb9, 0x17, 0x24, 0xa9, 0x39, 0xd1, 0x5f, 0xb0, 0xbb, 0x1e, 0xa1,
	0x89, 0x49, 0x13, 0x99, 0x53, 0x77, 0x09, 0x98, 0x63, 0xb6, 0x65, 0x24, 0x0e, 0x33, 0x4c, 0x85,
	0x4e, 0x00, 0x54, 0x49, 0x24, 0x5d, 0xbf, 0x26, 0x02, 0x8b, 0xd8, 0x8b, 0xe2, 0x12, 0xd0, 0x82,
	0x3c, 0xe3, 0x8a, 0xcf, 0x29, 0x29, 0xf4, 0xdc, 0x2c, 0x86, 0x56, 0x36, 0xaf, 0xed, 0x78, 0x7f,
	0x41, 0x9e, 0x1f, 0xea, 0xc2, 0xb8, 0xd2, 0xea, 0xba, 0xf3, 0x5b, 0xdb, 0x4d, 0x32, 0x69, 0xdb,
	0x45, 0xf9, 0xe6, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x7f, 0x3b, 0x54, 0x2d, 0x06, 0x00,
	0x00,
}
