CONFIG = {
    'project': 'v8',
    'source_vcs': 'svn',
    'source_url': 'http://v8.googlecode.com/svn/branches/bleeding_edge',
    'status_url': 'https://v8-status.appspot.com',
    'error_recipients': 'machenbach@google.com',
    'masters': {
        'client.v8': {
            'base_url': 'https://build.chromium.org/p/client.v8',
            'builders': {
                'V8 Linux - builder',
                'V8 Linux - debug builder',
                'V8 Linux - nosnap builder',
                'V8 Linux - nosnap debug builder',
                'V8 Linux',
                'V8 Linux - debug',
                'V8 Linux - shared',
                'V8 Linux64 - builder',
                'V8 Linux64 - debug builder',
                'V8 Linux64',
                'V8 Linux64 - debug',
                'V8 Linux64 ASAN',
                # TODO(machenbach): Enable once crbug.com/382930 is resolved.
                # 'V8 Linux - nosnap',
                # 'V8 Linux - nosnap - debug',
                'V8 Linux - isolates',
                'V8 Linux - debug - isolates',
                'V8 Linux - nosse3',
                'V8 Linux - debug - nosse3',
                'V8 Linux - nosse4',
                'V8 Linux - debug - nosse4',
                'V8 Linux - deadcode',
                'V8 Linux - gcmole',
                # TODO(machenbach): Disabled until enough slaves are available.
                # 'V8 Linux - interpreted regexp',
                'V8 Win32 - builder',
                'V8 Win32 - 1',
                'V8 Win32 - 2',
                'V8 Win32 - debug builder',
                'V8 Win32 - debug - 1',
                'V8 Win32 - debug - 2',
                'V8 Win32 - debug - 3',
                'V8 Win64',
                'V8 Mac',
                'V8 Mac - debug',
                'V8 Mac64',
                'V8 Mac64 - debug',
                'V8 Arm - builder',
                'V8 Arm',
                'V8 Arm - debug',
                'V8 Linux - arm - sim',
                'V8 Linux - arm - sim - debug',
                'V8 Linux - arm64 - sim',
                'V8 Linux - arm64 - sim - debug',
                'V8 Linux - mips - sim',
                'V8 GC Stress - 1',
                'V8 GC Stress - 2',
                'V8 GC Stress - 3',
                'Linux Debug Builder',
                # FIXME(machenbach): The builder has issues since a restart.
                # 'Linux ASAN Builder',
                'Android Builder',
                'V8 Linux GN',
                # TODO(machenbach): Disabled until stability issues with the
                # windows bot are resolved.
                # 'Webkit',
                # TODO(machenbach): Disabled until layout tests are more
                # reliable.
                # 'Webkit Mac',
                # 'Webkit Linux',
                # 'Webkit Linux 64',
                # 'Webkit Linux - dbg',
            },
        },  # client.v8
    },
}
