# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: api/api_proto/issues.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the api/api_proto/issues.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJzlWktvG8l2dpPiq/RqkrIkS7Jcpu2xJFOUHzfjyUxmxpRE25zIokJS4+tsPC2yJfEOxWbYTc'
    '81Lu4PCJDd/QEBAmSRrLMOEGSbHxAgQLLLXWabxV3kO6erq4vy2B5gkE0iwHDX11XfefTprnMO'
    'S/zDglhxhr0d/Hs9HHmBt9Pz/bHrV3hQyF54A2/k9Porq2eed9Z3dxg/GZ/uuBfD4G04beUSRc'
    'e7wDp17+aP0L/2Tn7ldgIlpfRXlijsjVwncOt0t+n+BTQICmWRCkZOx122pLUx/XCxEilTUTPa'
    'dLcZTircFDNgI9rXA+fCXU5gUa45rbBDQIU7IsXil5NMOB8ThnLDu6WhmH/mBj9DlR2RC80cua'
    'esx/TDwmVZ7mkz21NXpU/FrEL9oTfwDU2tD2r6j5a4tu/2XeW4PfjdHQT/a/67JrJ9r+P0X/e6'
    '7MJkM8PjerdwXYhOKJ1uTvHNnEJwe1Gku6zncgq3sk01evh7S6RZdb/wVEwbMVBYi7V9NzRWlt'
    '5xZ+i40pXCE5GNnl7hWjzt0hP9EENLFN51auFWvOC9Ll9ZrISvSSV6TSo1ek1KV77551mRtVP2'
    'FfuhbYn/tLIzPCg8/DdL7nnDt6Pe2XkgH95/8Jlsn7ty73zkXfTGF7I6Ds69kV+R1X5f8iRfjl'
    'zfHb1xuxUhj31XeqcyOO/50vfGo44rO17XlRieeW/ckduVJ2+lI3db+9t+8LbvCtnvdVzYiTVO'
    'IDvOQJ648tQbD7qyNwDoyoP6Xu2wVZOnvT7IR9IJhDwPgqH/+c5O133j9r2hC42UoXjGOwAG26'
    'H4HUXv75z4XSGy2YSdsbO2jctk9oqdw+g2X1u2wPUtvk7Y07jeEjPZNObMwS9FOIlHmDeH9XNi'
    'jkcJ3J+3E3ZV2NEYM+bttJ03kASQon3HQJJA7ttfahbLtsHyhZ5hMZKGnBhJ2PR3w0CSGG/Zjz'
    'WSsPNgKdgbMQKePHiWDYRmrdiPDCSJNfPww53sFOxZgr2rtrWyJA/dXwfSeYMQc07g+8A5+1z+'
    'QsARU2zmEhyxAhOmlCOWIfyaKETj7BQjS/YaREVYmrE5A7GAzNsLBpIEsgSVI2bLvoY1K5rZAj'
    'Mhy5BmayzFWNZAaF3OvmogSSC0KmIGKzlMMyfATMg1SLM1lmYsYyAWkKw9ayBJIDYeOrnQsm/A'
    'haX3uvBR6EKLJ2btJVbHYhdK7UJLuZCQG8pQS7lQahdayoVSu9BSLpTahRYrfHOCmVxIiDSYLT'
    'ATJgyE1k0bzOTCm8xMhibsT2DoxnsNfRgaSuI/gaFXWZ0EG3pX+z2hDCXkEzjD1liasYyBWEAi'
    'vyeUoXe135N2OfyevUedT0N16F0vg+Ymq5Nkdba1d5JKHULK+B7YGkszNmcgFpDI70mlzrb2e5'
    'INr+jQTSq/E7Kt/J5UoVvRoZtUfq/o0E0qv1d06CY5dHew5qpmptAlpKJCN8RSjGUMxAJC378Y'
    'SQIpwoqIOYkvE15bzZwEMyE7hj5JMN+fYCav3gdzwUCI6aq9qJmn7Af6sfNYIffVYw+xFGNpA7'
    'GAZNRjD5EkEDz2kzTva4/EfyyKDyWEhflL22ApI1K8E+6+EUVsGZe3yV3Bd49oeGT9+d2zXnA+'
    'PuHN5czrO4OzWAymDbG9sLT/tqy/SSSfHe3+fWL9Wch4FG28L91+/08H3g+DNs3/5m+vYv9dR7'
    'w+wsP4lxnsv+u8//7TjOQlHa8vd8enp9ja5LYMye76susEDjbGwB11zqEGbZWjC9oRzU37/mdq'
    'gawPOhX5nr36w3voUCmxfRIqsSOEbLrdnh+MeifjoOcNpIM9eoydG/u02usJOekNnNFb1ssvyx'
    '/gONq06X9vDD0vvG7vtNdxiKEsnZErIfmiFwRIDSDzTa+LC84FaO8/9fp974fe4AxpxKDbo0U+'
    'LQKPG3wOlehv65JiPqUgZvZxMfYDWB44KqNwTpCL4JbymJADL0CaUA7zlj6oiMGUOOheUgfyOn'
    '2nd+GOKu9TAsIMX0RKwMbuuOPGeohYkZ+lh4jypa7XGVMO6EQPaQf+93BnJBEp7qjn9P3Y1fyA'
    'cFNIU3tt1KHb45VETGk4KWTGFjJQfY/93gt8smgQUiFVhNC3lNMhUqC8J91BFyhnclDiwgtcGf'
    'oE0dmFdghOeYobIsoiT4MfKExUBEl/6HYogrCqR4E1otgZhFHk+6y7kO3n9ZZsNZ62X1abNYnr'
    'o2bj2/p+bV/uvsLNmtxrHL1q1p89b8vnjYP9WrMlq4f7QA/bzfrucbvRbAlZqrawtMR3qoevZO'
    '2XR81aqyUbTVl/cXRQBxvom9XDdr3WKsv64d7B8X798FlZgkEeNtoCueuLehvz2o0yi313nWw8'
    'lS9qzb3nGFZ36wf19isW+LTePiRhTxtNIavyqNps1/eOD6pNeXTcPGogHybL9uutvYNq/UVtvw'
    'L5kClr39YO27L1vHpwMGmokI2Xh7UmaW+aKXdr0LK6e1AjUWznfr1Z22uTQfHVHpwHBQ/KQraO'
    'ant1XMEfNZhTbb4qK9JW7c+OMQs35X71RfUZrNv4mFfwYPaOm7UXpDVc0TrebbXr7eN2TT5rNP'
    'bZ2a1a81vUAK0v5EGjxQ47btWgyH61XWXR4IC7cB/Xu8etOjuuftiuNZvHR+1643ATT/klPAMt'
    'q1i7zx5uHJK1FCu1RvMV0ZIf+AmU5cvnNeBNcip7q0puaMFre21zGgTCiTAptlMe1p4d1J/VDv'
    'dqdLtBNC/rrdomHli9RRPqLBgxAKHHbDU9KOglwmsjdMv8PGX9qazuf1snzdVsRECrrsKF3bb3'
    'XPm8ElY5kjPLbDaLRPQKKotZXP4+k72ihvNqiJkl7K1LIq8BnkNQ0YCwB4egXpgBsGJ/ziJugf'
    'OrSISlhmomFS63sDQfiQgz3RAqGhAvJFAvRD1mL6BKIhG3wVmORCTUUM1MMJCxi5GIMMcMoaIB'
    'QUQI6oUo/+xF+x6LuAPOe5GIpBqqmVQU3sHS1UhEmDeGUNGAICIE9cIMgHVUkySC8uVSJGJKDd'
    'XMMJ/OIH/LawAiQqhoQJxOE6gXJgFcR0JLIu6C82YkIqWGamYKIu5i6XIkIqWScYKKBsSZNoF6'
    'YQbAqi1ZxAY4b0Qi0mqoZqYhYsOMqDSL2DAjKq1EbJgRlYYVG4iodfGHBNehj0Brr/xXAl+/M3'
    'eAnaEjOcnC1u/7zpnqGLz1xtw1GLnblItgg3HeeL0utpLT3oB3yPGwT/mG2xWT63mHxvKRrB7V'
    'qaMhkclhZl+6v3Yuhn3uWoCPUxwUEz5vdKOwsyKk2vhGqk9Di3l3hC7go/zk3OtW5FPM6w38wB'
    'l03ChhoRQM+zzuefI3ISTlaNiRu85o40cbNpuUvoxHSAHec/+LkOa3tPdBq29a+LpRsoF0L8oE'
    'kIXI73j2d2RZ6AueGHY/5Xe/+e13lbi8f0Slls6w/3LpcmPW7KrGjdnSn4gZs51XWBCpwPveHX'
    'DXL9cMB9SAG7mO7w1UX0+NSlUxs+ddwKPcxDotFMTU0AnO1WK+pt5ez3+tcgVen23mev5+CJQ2'
    'RfZpz+13aTmmntJ12EIMSXKMUAOx9LXIHjgnbp+mQs8+XUd68uBjshyRa8G9Y58YYJPPA0WhRs'
    'Rx4ToD/zX1pSIORhoALolIXhbxXGSjDu07PVHrwz1REjWre6KlrsgcI/SIaElkENYjmkQcU800'
    'DetdkoA8cNh33k50XRXGEj6s7zf/WkBhM4N3t2pb4g9JFDYz//cbiw9/l4A5UIa5+NuD74t/4c'
    'CY6E31Q00ol+0NOv0xZd/4qAydUUCZM0qacT/o0XdHfR98Umpr8rcJebTrU4Jboja9enF9zrep'
    'uHEH3vjsHPRhVRi99Y48rtOXTD1FAQ/S54m+jkDJFfT0y1xeoCgYBL3Tt3STeDA3Lsc6/R7ukj'
    'NF9CFEQccGYSZl7TyNn9pIJSJz3G4IW4sFm9qLH+mL0bengEUL4r5uLRbthF0sSfnLVvOp5C9I'
    'LO15+8UBvHjmQqDZfCxyL3TRaCymGMsaiAUkN9GOTALJ2wVR083HBaxZKP2RbAzJodgeIsuH49'
    'HQQ4CxJso15O6uezI+O4MDDYWo8UNERSQfZs9y4Z2e5QIUmp/oWS7AjKLqLK7Cg+s/pbO4yh6M'
    'O4truvMSdRYJWVX+sZR/1rQ6UUq2BnVmJzqLa9xwizuL17FmcaKzSMia6gRZytDruqcTdRavc7'
    'Jndhavw9SrqrN406Yc8Sd0Fm9yfMWdxRJ1hic6i4TcVOoklKElbWiUGJZgaHGis1hCZrikOouU'
    'Rm19zO9J1aC0jc7iBj30ic4iIXeNPhmpszHR/wtzo9xEr5GSI4rLuLO4qf0edRYJ2VBGRJ3FzY'
    'lemsXrIr9HncVN7XfqTn6ohaq6/1PcoMyqMAjzVGo0LrA6U8rQsB0ZqjOlDN3Rhkap7I6O9yll'
    '6A7He8RscaNxUTNbuh25oFdZqh2ZNhBaFxk6pQy9z4ZGzAluNMbMCd2OXNSrEhPtyCnVQn0wwZ'
    'zgdmTkwpT9KVz4xx+LlRRoPtWxEubhj3WvOKVcSMinKlZSyoWPtQujVP2x7hWnlAsf615xihX+'
    'TBuaUi4k5LHqFaeUCz+bYLZ4XU4ZmlIu/Ewbmra/DHf5D8dKGjRfwtB5ViesBr7Sreu0MpSQL5'
    'WotDL0K61OVDB8BXVsA0kCodZ1VSGW/TW5sPQA2S10KdMG6p34nTHlB/3e964s0U43qFQqT1SS'
    'T/t6SX2o08o3RPKV8mha+ebrCWUsFpWbmJMEEnk9zeH1RHs9rcKLkK+V19MqvJ7o8Eqr8Hqiwy'
    'utwusJeV3n4r+7Lj5+isE4K/GBxL00EoKz5W+d/phPCoT5Mp0UsC6fFIjS6mb2NEqwkTW/oZUq'
    'UQwHH0tp/y4jUuEP4j8roS0si4w/vrhwRm9ZRq4ZDQvYH8Lkmw2ZYkOKsSE6Z2/mfJ2+V0TO+w'
    'F1Ji9J8ZJ8vERlzs0sz6H5WyLT6dBkfzktkz8+O93p4D+/8EAIrifC6Rmebjg2KkKaub668gtf'
    'irlOVAmFy7K8zDg2YVZKzdmOMfILNXH1BH763u2+9gav9fEPfzl3Wbg+/1FQCxqDCPILu6LIKL'
    'IZk0S8lyQfTY85oMqFOzqDJr1B4MU0y9PvPYpSCBfUMV8XP4/FTBibHGP+8gzrsHApPDmOm9On'
    '+trX0UiHJLrLs3E0MlD4hZhBpeyNAvXo59736KejaaTNprCpGoBRQe8C2SA+JsvzWJlpzod4O4'
    'JpaqePRNGcaodTQzyeui0K4Q8kE5PzPDkf3YmnX+cwH73uoKwJlgv8dlBEj/YIoCoPhvtD52K5'
    'GB5z6fktjEgjJwiczjkfkAlXL/Dq+Rhnjm/+egHlXBYf+grKuX9PoJzL/j8o5978SDUX13GU5I'
    'fH0rhkGrl9ai/Jk7FPE30R1WVl6VbOKmXJwSjDsC1LdQrJD+ut2N++KpiEcT5lhs+khMWTDb8v'
    '/JRzGTb/DBufy8i/cy6DEHvizEWaMTFRGuX1T/9RaZS/dC6joJPbqMYhJH/pXEbhnRqnMFF0WX'
    'wAJW/onOBCbXHiXEZYzsXVU0KVc+mJcxlFvXVG5zKKnLB8wjnrchjHK8s/XlQ8iMunZT5nEJdP'
    '8QmUqHwKT6DMT5RP8QmUqHyKT6BE5VN8AiUsn1beKZ/MEyhR+bQywWzxutyl8mlFZ7cW+3BVZ1'
    'mW8iEhK0bJRz5cnWBOcOkYZVmW8uGqPiBg8ZhLR82c1MVkbGkSEUXYtIFQMTljSE8y0zV1hshi'
    'Da/r6o3Huphc1aso8SQsZyBUTAoVGyFCxeSicbQmhao5wYen1BjM6xOHXVLgXUfEFwzEAlI0nk'
    'QKvOtgXte8afsGWG7pGWnw3pjgTfOcaUO7NB/8WQBLjCSB3LRLmjfDh3zu6RkZdRRIGAgdBJpW'
    'RydChA4CLdufGAgdBNq0tzRvlo/4VPSMrDoIJAwkzYd+igZCVfaCvWkgdAyobG9r3hxX1Nt6Rk'
    '7V3cJA0kBM3hxX3Qv2XQOhqnvLLmteYd+ic0E6IgR4CSkZsgSYb03IEvxb0rQtDSQJ5JZ9RzNP'
    '27epXNYzpsF8e4JlGry3wXLVQCz+vahkIEkgd2BDxDuDUXR8hsfgJeS2IWsG8XhnoiEyo343yh'
    'sI/QS1gPflsUJm+TzU2spd2W7sNzZ+NfJOTnoDf/NzeXTu+Gozcob0077T91VNwwvV8ao7RrDM'
    'quNVOQOh7oUwXtBZbnxcw8sXGTfHnQqpmed0P2NNr5pT/YycgVA/Qxgv0hz3M67jhYyY57lTET'
    'PP635G/BDnVT8jZyDUzzCZ57mfYTLTGUkEjGbGTEY2DWYbzFsTzDaYt8C8ZiBJIDfUuTFC8va9'
    'iVN1eTATsmUESB7M9yY+sXkw39PNphBJAlk0zusV8HJF7RQeg5mQe8Z5vQKYyxNBVOCTbRnjbG'
    'CBD8XlVTuFkCKfYruhmYv6rFt8yq8I5u0JnYt81i1nSC/yWbc1ez2qSv8HG+UsgQ==')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


IssuesServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'api/api_proto/issues.proto']['descriptor'],
  'service_descriptor': _INDEX[u'api/api_proto/issues.proto']['services'][u'Issues'],
}
