# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: api/api_proto/projects.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the api/api_proto/projects.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJzdW1tvG0ty1syQQ7IlS63RxRTly5iy5JtE2bLs3fVdsnSyvvtQ0jn2QbDCiBxKs+ZtOaT3KE'
    'DyEwIssj8ir8l7nvKePxAgwL7kNX8gAVJVfZkeUbKNBfZlYdhgf9NdXVVd3VP1TZv9yxy7EHSj'
    'Vfi73+11+p1V+Pe3Ya0fV6jp5VuddqcXRM1SKd2v1mnBI9GrtHCqjP3OgSGq/D2beh3F/fdygm'
    'r4u0EY9715VugGh+F+HP1dWLR863q2mkdgB9reRcboYb/zKWwXbXhaqFL3XQTKLTadFhl3O+04'
    '9FZYXtkBIp3ro2uTFWVIRfau6i7eEptohz/394emOofwez1djfG/CfvPO+1GdKjUX2bZfi+oCd'
    'VH12aTeWSPXXxaFZ28K2xMOacdtEI5zajE3gJUbrN5nGQQ9zut92GvFcVxBEb9xeZ7xi6cPp/0'
    'pc9GuwlM7kQJCVT+xIog4Ycojg6a4ZuwdRD2/nLq/j2bO2UyqWuFFQZx2NvvhY1TFn4PHlXDRj'
    'U/ED9i7zZjh73OoCsG2GcNKFAnHLH2J5vlVbh579iYGX7exWToKZFeunTWY6F9ecR7yAo6wLxS'
    '0v1k1JV48kw8gMGHbPq0hfQW03LOCKzS0te6aS1/wyaHlsArp4afGgylhS/2UfJf/pGzPM/yEf'
    '6YW+y/rfwYNby1/7T8553ucS86POr7a7fv/NLfPQr950e9TisatPyNQf+o04sr/kaz6VOn2O+F'
    'sISfw3qF+bCYfqfh94+i2I87g14t9GudeuhD87DzOeyFdf/g2A/8zZ2tlbh/3AyZ34xqIagEY4'
    'K+Xwva/kHoNzqDdt2P2gCG/usXz7ff7mz7jagJwnt+0Gf+Ub/fjR+srtbDz2GzA/skrhx2OofN'
    'sAJH5ioA7RUx/aoUH68exHXG8nmb5+EPh59OfoQznuML9Nvio/B7mY3lXcDHwRdT4BhqwbNxGj'
    'NOLRueT3Cbv2RctaHHBHe5ZyA2INP8moE4gKzx77QUi3OQcl/3sAhx+YSB2IBM8isG4gCyzNe0'
    'FBue2/xA90C5kyClZCDY5wL/hYE4gGzy32gpDvdAykfdA/3hgZTzBmIDMsfvGAiOesT3wEsZ8M'
    'ks+GyOfJYhj8yCz+Zhhoz02XmYYZZ5qp3PCIRfBIkKyxKWMxALkDyfNBAHkGk+oyVbvAhjilqy'
    'BZIROQ+zcY1lCcsbCI4r8CkDcQCZBZvRAgs8NsIvS3ssauf5BZrVInsugjyfRlvSHkSYgbiAjF'
    'JUKMQCZAq8kiAOIJf4ZS3XgpYNPvFUG+QSYsyF1lzS1ljSmktgTdFAHEDmQeNFQGy+ANYscat0'
    '3n8Lr1s/+AwHRAAng98PDh/4dxmZidMvgJlFUscmM6/CRHOkji3NRGSBAkxhLmHjBmIBAhvAQB'
    'xAzhuSLb4IY0paMhqKyFWYjWssS1jeQHBcAZY/QRxAijAKDXX4DTB0+WuGYnzfAEMXSB2HDL2p'
    'DXWkoYjc4Is0lSMNvakNdaShN7WhjjT0pjbUIUNvaUMdaSgiN6WhjjT0ljbUkYbe0oY60tBb2t'
    'AMXwVD75xp6JowFAN5FQy9SupkyNDbMFGZxGakobd14GbkNrwNgTtpIBYgntyqGWnmbe7D0YTK'
    'ZPk6KPOLr3k9C2LWQRmflMmSMve017NSGUTWpYJZ6fV72utZqc497fWsVOee9nqWvH5fez0rvY'
    '7IPen1rPT6fe31rPT6fe31rPT6fe11lz8Qr8wvG+qCmAdg6BVSxyVDH8JEV0isKw19qL3uSjMf'
    '6uPClWY+hOPigoE4gFyWDnTJzEd6NV1p5qOUXAvkPkrJtWjUlFxNVxr5CFfzwKUy4i77P599oR'
    'ZJKpbyP7AxM8n0piEXpeTeorRSNLxZ5vbCIO6onF+2sPToidH7Ub3oiNJDIi/qmKr28VlQq0FG'
    '0C9mRKqK2IaAyhts7HmnBVlN2O5D8uh5LNMN+kdyevqNs0Txfj3sRZClkAb5aiGKtwRQ/j3Lfx'
    'eFzToOh64N/C1SYyGkQAgmxt41lukfd0XOPL42laRaJGAXHlWpg7fAzgVd8NXnoClECdvGFEhp'
    '9lOWfx0chE2cGPzWxN/Kb9T4muYBK+z0g/4gRgng45gaUoRsoYxWGLTjfUyLlAxC3gFwYgrn5B'
    'S/ZvkXcTwIcYaTlYM1VDl4cyzf7NTA6Eioe66ao/aLernOcjLX986zHJUQ0AllZKouNsWC16O4'
    '2wyOU7WJxGiGL+t78w8WK+jF8EZZ7u27/d2P77f5iHeOFbbf7r0RTcsbA8ve7oqWja2d3apoOd'
    'h1b2dbNjPY3NrY3RbNLDY33717LZouDt2rylbOm2TnNt6/r777YUNC+Zf/XIJcewwOjj1IJ/7X'
    'gVx77K8/1177JxvMAWVIVj1sRO0QFG0FYAwdIgeDRiw0CXqgdbvWHNRB5yD2u0EPTO00mN8aNP'
    'tRF8aj1SA9RqVupjkP//1mXGHML0NklX35CFzR7gdgVdjuDA6PQHyj02sFfaiywGIwzN974cNY'
    'GVkMPNgKwZXtQ0TRFRiRy36AvqnD2RI1jvEhyoG+Qm/sVmtG8BSdyXx5cPmtDhkEPRuwlNSNVq'
    '1XERWIqCYWKWv2IBJKZ75P7jGdTnswaJrd1un0FJzyU2Xf/7BT/c6nUzaZ7de7b177SLTAhGbC'
    'jWM8Iy3GN/1UKi3GmabgBTieSrinoFzw2LZOuKdhzHT5nv+uiw4Nmtry7qDX7UCAkSbSNejuen'
    'gwODwEBxoK4asKBU2lcvAsYek8fRoUmkjl6dNgxhTblIjNZ7ACKK8lCom5V+JBtwu/6n7c7+Hy'
    'oS6wnPC+6Ift2rGhjQ3aoJRpmVUILEtY3kAsQMyqAWunGaoafiURB1qQeZRv+NuVw8qyfw1fV8'
    '/Cn4NWV+yZa7jbYDft66BQSjigBA6ekYm8wLKE5Q0EiyuVpKhSbFYnKVgKjPArX0tSRM2AQZXU'
    'NJcxQHTtgSGDyCUZMpYMmcup2gND5jKocy5V1VzGytWoanxd/amqBpHLRnWEa4+Ym6pqfKjKJ1'
    'NVjU/V3yJkZyOQ+I9AenuWob9CQ7Ok4CLPQkyPUwsNXZIJZVZHPSIFA7EBGQOj1BiLX4MeXPew'
    'JDJqIDYg4xCqaozNr0OPCd0DpVyX2ZlCsM85QzesYMwxolQxx2ApfiM1RpQqiW4ZKktM3bAEvJ'
    'nSTRQcyZisLFRGDcQGxBzjQmVljsE8dzk1BrJJQMwxOb6SsicHY1ZS9uRgzErKnjyv4FbUPfIw'
    'ppKSgsdohQ4BUd7e/WL9sZ6Ut3clk6PK23XNHajyFpG7Mi5tGfHrqSJ0hOoYdQqo8nadToGkvM'
    'WaZSZV3orKpmiUrqKyGU2Vt/cg7HiqvL0HZ+S0lmxTzTKvJdu6skmKYjtV2dhSI6xsZg0EK5s5'
    'qJFE4fwQXPjkWwrnh9qFonDGemMqVTgj8lC60JEufJQqb0eoBimkSmmsQfA9kxTOj/WhoQpnRB'
    '5Jx6vC+bE+NFTh/FgfGqpwfiwPDSycN8HQ774WK7iFNol5Sgrn5xSUnlE4I7Ip1VGl83NtqCqd'
    'n+v3lyqdn1PoKskW39KGZqShiDyX76KMNHRLG5qRhm5pQzPS0C3NjdEq8+2UZIwVRLZkHGRkrG'
    'ynJKNG2ynJGCvb2oVZ/hJc+OZbyv2XOlZEuf8qVZSjCxF5KWMlK134KlWUowtfpYpydOEret8l'
    '5f5rbagq9xF5JXkqVe6/Hir3X4PkyVS5/1ob6vLvRdb+5VjBY/B7MHTCKPereverch+R7+VUrj'
    'S0qtVRBX8V1OGpgr9Ku39DF/w7lF3c8cMW6LKMCXHnIK4NMN9vRp9Cv4yZa7tSqZg5R1lmGYoj'
    'QCFV6VFX+mYnpYxFUxVSfRxAlNddCq9d7XVXhhciO9LrrgyvXR1ergyvXR1ergyvXfS65h/+dJ'
    'd9y/fOb/t0Wv7IcvJDEPIDRu1Kv70iy8WDVivoHcuCUzXxu1w9jGu9iPJKWcSbUPmPlqrBt/78'
    'GhyU6gXtTyT/XJV+exdYod6pibxVEh8J4F1irB52e2Et6EMVnCWBBlLuSWph60xqQc1pnzWn8+'
    'U5M0Nz/sExuJitM7iY1BT2ySluMxbUW1FbfCt0zvxWSJ3o6+JNlqvVRPfMWd3dWo36fsVpGAe1'
    'XkgPXXiYq6qmt8ZG6WeHPnsWc/Sd9ZSZmOyFJAcU/a1OPWpA+VHMkzjd9tbZmPwtBBbOEjiquq'
    'HEO4zR2glzGZnrGd87JZdULTTlr7j8b7Ykt3A9VpmgsmhK8a3YO0Fh0afbhmLDrrGJAAuoGh55'
    '+5r5KlTHE5h4lstsNIr3sQqMepqVYRF9lEQEeSHo0I5qR6GMnFwUv8Wmt8jG4RFV+p+D5kCvzL'
    'kofpOA6cBxvxw4uW8InKs0bfcoiMN9MpgWKV8di+L3CJI7yv9osdENydn9WS68r4hA9cX8zA/g'
    'Y6ofqYcnyQDKw2O5D2Wr/D8Oc+W362+g49bZqDiB9uvJ3AZtqU+uKovVz9jbZtOiFcKB1WiA5q'
    '2wdxjK/Tg0HJX31IB32P8Ndk/CtZ7szpPhuqXDlWb+JSuGP9eagzj6HO6LwbA7G9HPYQxRgZci'
    'ZvVzGv9ePvUes/GaOnvEhC5NOGt+xE/Opuq5mtGKUVexrvUkfk4uLOnakL9i74FB8dKoPI2aSU'
    'YZgZMwv1vi1JrshRi6sHb9zv6nduf3bToE8tUJ9WC38wrhl/+xyPCT9Qjf5xb7Lzs/Ro2/dvbw'
    '8ynkYUIbEo+DtHRMDF0vbOIx7R9AYEDHmCkacNkPiYOhVfPpJAEMcwNY+FjQe0G/H9SOCJD8HD'
    'NuCIzRDQHB1XHw+/TXksER+oyvkkHBNkxqWkUxcYjw1GftLGFpJm5S0yqKiZvUtIrgJDydZipK'
    'DZFJmU8rSs0botQ8nWYqSs3TRaZgLqb0hzlFjwn2MGGd7CH20JbsoUmhIXuIH+YEM1UEF14604'
    'X3E2aqqGsvwUzN6dpLMVOIFGXtpZipuSFmak7XXoqZmtO1l2CmSkPMFCJz0gjFTJWGmKnSEDNV'
    '0rWXRS6cT7Fp6EJESgabhi6cT+mMGs2n2DR04XyKTXP4BbzfoCUjbYjIvMGmIW14ISXZoTsMhV'
    'QflDQD+ijJ4g5D4o2MRC7QTRCFZQlzDQTvNZjeyNC9BlVG2bwMy37tayw3ml4+Qc8saG5B0TOI'
    'lE/QMwtD9MyC5hYUPbOguQXh5Kt6cRQ9I+41JKQOLvvVodsHV/XiKHrmql4cQc8s6sVR9Iy415'
    'DobA/da7DlvQazD95rUIsj2kt6cWy57IgsysWx5bIv6cWx5bIv6cWx5bIv0eIs0ULdgsW5D4tT'
    'PHVx7txJmJ9bmi4WzM+y9qFifhC5JQNcMT/LQ8zPsvahYn6WtQ8F87OifaiYH0SWDU4JV2eFn7'
    'wysaJ9qJifFe1Dh1anor+XO3J1Kvp7uUBcQEYNKTaxj+p7uSPXokK3H5Rch68ina17OHRBw5Tr'
    'gNzVlFyH7mZMyVrZkSuziheCtFxxNyPhwDISWTXmytB9DZMDy9B9DZMDy9B9DXU8ORSBd1KSsy'
    'AZkdvG6mVlr4KBWIAwQ3IWJN9JSXb5GjcvvLggGZE7hmRX9ioYiAUIMy68uCB5TfMNiOT43VRc'
    '5EAyImuGD3Og892U5BzRvszwfA4k303FRZ4o3nktOa+J4PN6VB50Xk9JzhMRzAy78kQEI6mqJB'
    'eI4r2qexQkEcwMBGngUYPVLBANPA1xkCBIA1+RqUiGrqFsf/nDh+AwH+gDVXCYD/VrXXGYiDyQ'
    'zhGYa1xNURwmXk2ZNhDki9V9G3F0I8F7McVhChp4LsVhJjSw4jAf6XtrisN8RPfW7ucVh/kEF7'
    '205O++23p3/be9zsFB1I5vPPCN2hSqhHqEVTxLcZ1PiC5Ori1h2D8Z4jqfwFbxDMQBRAVHhtpP'
    'U8wvbm5EnsjgyMiD92lKMm7vpyB5wkBQksn8ZvgzvVUycnsj8tTwNW7vZynJuK7PQPKMgTiAqK'
    '2SITs39FbJyO2NyDO5VTJye2+k1gO394Y+QjNye2+kvOHyTW5eIHOJUjfjxaU+o4YUl9j0KWMl'
    'cHNv0hH6txLJEb9dKr0eWmfI26M6fbtf9pM78f5hL2j3ofgXaXy7048aGAL4qEPkXFxJoiEnOf'
    'VNQ/PcEKeek5z6jIEgp64+rWb5iy8y3+sJ8/0CNt6UwXy/5CcvuiHyIsVqu4SxFPP9Um88xXy/'
    'PHHRDdnyRYPBFpw6MxAXkFGDY7do1JS8Uqp471eQ/VzVcm3iyqe1xrZm1JO57CFG3ZaM+oSBIK'
    'OOQY/ZhmDU97+abShKffwEpV46hVI36fKzKPUZA0FK3WSxBaW+aPDcgh9P36Hb0euQsOMz0oMJ'
    'O648mLDjFYPlFuw4MxAXEFOu4MZn+I0T3PgyX9FyHb6HmarugcfRXkou5hp7+o3iysNoT79RXH'
    'kY7cEbpazlZvgPmFnoHhmJMAPJAjJqMPd4FP0Aq3vTQBxAVsBuJTfLf8SsUPfAo+jHlNws6Psj'
    'yD1vIBYgRb5kIA4gN2AmJdflH1J+wIPoQ0quS31MP2BcfUj5AQ+iDyk/5PhHkJKsAB4dH1Nycy'
    'D3I8idNRALkPPyPe/Kg+MjFD3X2b9bEsrzn/AdWf5Xa+iI2w1bXeQw4mW/FRwfhP6nMOwiqdLy'
    '47Ab9OBRhQ2N2gobwaDZ9383CHvHdAoe9qJ6cvoNDVDc0kq/s0Kk03CXGv2nlH1iV/bDdr93vD'
    '/oNZOvR5gZoRkfDQ/lYY1/Sn3jwczoJzhIiwbiAAIvdvWN5/8BeW78iw==')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


ProjectsServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'api/api_proto/projects.proto']['descriptor'],
  'service_descriptor': _INDEX[u'api/api_proto/projects.proto']['services'][u'Projects'],
}
