# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: api/api_proto/sitewide.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the api/api_proto/sitewide.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJx1k81u00AUhT3+SZ3bliSTKjalKVdlAUJqAikL1F0pRaJCBSUgIbGoHHsSWzgZ45mE9v14C/'
    'Y8BCtmJk4pEl1YmnN/vnPGsuH3BuxFRdZXz2VRcsn7IpPse5awnpHUn/E5L6MsPziH9pBNSibS'
    'j/wrmw/ZtwUTku6AJ7UObSRP6sOVoF0Ac7gsIpmGjmnVTeWDKhx8hp1/WaLgc8H+wsht2FNorW'
    'DsqsjU0qVgsbHbHjZM42xVH7F48AX8UXUD+h62brvQbm99md5/brK7f1d7Fe7AOv/hQY26nnWf'
    'wC8CZIs6nkUHPwme8uK6zKapxMGz5y/xY8rwNC35LFvM8GQhU16KHp7kOZohgQrOyiVLeoCfBE'
    'M+QZlmAgVflDHDmCcMlZzyJStZguNrjPDV6PWhkNc5A8yzmKlAaieSGEdzHDOc8MU8wWyuigzf'
    'vT09uxid4STLFbzESAKmUhbiuN9P2JLlvGAq0ZTzac56MZ/1VWF+uLLvV3jRH4sEwAdiU2fDbw'
    'KAXbOoW7c2iTo7NYtQp67qm+DWLNuiDtjnsAWeFqqlXtVaKQDsPF4rR6nBG3gEtqtwDYuS3QAv'
    '2JXEaKlefjRWoWU0PcYXoH1cDWv4D7SPa3yadhu2wdPCpW7TbnQ1WktPN/21UnvN+r21UrbNFq'
    '0oqtWyw4pCFKVlN9vVJPF0c00herR+01OUVicw4Ql1O+pTuCP80Sq8Xu/4e8aW6PBBFZ6Y8IHd'
    '2TdoYsIHlS0x4YMqPDHhgyo80eFD+2FF0eFDO2hXkzp8eEPR7mF9d60UJezuj2vm1z76A/XT05'
    'E=')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


SitewideServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'api/api_proto/sitewide.proto']['descriptor'],
  'service_descriptor': _INDEX[u'api/api_proto/sitewide.proto']['services'][u'Sitewide'],
}
