# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: api/api_proto/users.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the api/api_proto/users.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJxtk8Fu00AQhrNOnGy3qTM1SQlISKMcUA9tXFIhIQ5IJVQIhDikcEZOvIkt2d7gXUfKA/WpuH'
    'PhJRhvnTRIHCz5/2b2/2JHFn/a4lm4TgK6fqwLZVRQalnosb33eaZyVYRJOnopvI/SfKfZTP4s'
    'pTZ+X7gyo9GQITs/mj2E0YVoVUv/n/qecJJo6BBqzuhu8k641bb2X4tOXe8Pxzvp+F/jc+9xUu'
    'FR4/O9Kzi40ICnwMRvxrs2+JNfDKdqvS2SVWxwcvXqDX6LJU7jQmVJmeFNaWJFD4k3aYp2SWMh'
    'qXIjo7FAKke1RBMnGrUqi4XEhYokUlypjSxkhPMthvj+7sOlNttUCkyThczpmIlDg4swx7nEpS'
    'rzCJOcoMQvn6a3X+9ucZmkVF5gaATGxqz12yCI5Eamal299pVSq1SOFyoLCOSXD/qgrtfBXEdC'
    'cO5ABziA6PI2b4CgZ+7SC7CJM8ocToRnk0PzY3DgimCdaeMY2rTxSBwiPXhxQJpEzuGCOlvU0C'
    'PDqTW07PkeGc7I0KoNQIYnwt9l3rKkB0Nq3DHXMn5AGJEj8A5Ik8gp+NbDoF//sTbZzKFrrcxa'
    'B3srq60V6deNrLYO9lZWWwd7K6utA2vdNTM4q379vplRc0UGZIM9cy3rHJDqHAdxQJpETsCbt+'
    '3ndP0XohKa/w==')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


UsersServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'api/api_proto/users.proto']['descriptor'],
  'service_descriptor': _INDEX[u'api/api_proto/users.proto']['services'][u'Users'],
}
