service: default
runtime: go111

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /internal/.*
  script: auto
  secure: always
  login: admin

- url: /admin/.*
  script: auto
  secure: always
  login: admin

- url: /.*
  script: auto
  secure: always
