application: predator-for-me-staging
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_concurrent_requests: 40

builtins:
  - remote_api: on

handlers:
# Static resources and home page.
# Web UI pages.
- url: /
  static_files: common/static/robots.txt
  upload: common/static/robots.txt

- url: /robots.txt
  static_files: common/static/robots.txt
  upload: common/static/robots.txt

- url: /common.css
  static_files: common/static/common.css
  upload: common/static/common.css

- url: /.*
  script: frontend.main.frontend_app
  secure: always

includes:
- first_party/gae_ts_mon  # handles /internal/cron/ts_mon/send

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*_test\.py$
- ^(.*/)?tests\.py$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- __init__.py
- backend/.*
- scripts/.*

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: 1.6.1
