# Copyright 2016 The Chromium Authors. All rights reserved.
# Use of this source code is govered by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

application: monorail-staging
version: 2015-05-26
runtime: python27
api_version: 1
threadsafe: no

default_expiration: "3600d"

instance_class: F4
automatic_scaling:
  min_idle_instances: 25
  max_pending_latency: 0.2s

handlers:
- url: /_ah/spi/.*
  script: monorailapp.endpoints

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /database-maintenance
  static_files: static/database-maintenance.html
  upload: static/database-maintenance.html

- url: /static
  static_dir: static

- url: /_ah/mail/.+
  script: monorailapp.app
  login: admin

- url: /_task/.*
  script: monorailapp.app
  login: admin

- url: /_cron/.*
  script: monorailapp.app
  login: admin

- url: /_backend/.*
  script: monorailapp.app
  login: admin

- url: /.*
  script: monorailapp.app
  secure: always

inbound_services:
- mail
- mail_bounce

libraries:
- name: endpoints
  version: 1.0
- name: MySQLdb
  version: "latest"
- name: pycrypto
  version: "2.6"
- name: django
  version: 1.4

includes:
  - gae_ts_mon
