/*
  Action types.
*/
export const ACTIVITY_TABLE_REQUEST = 'ACTIVITY_TABLE_REQUEST'
export const ACITIVITY_TABLE_RESPONSE = 'ACTIVITY_TABLE_RESPONSE'
export const ACTIVITY_TABLE_RESPONSE_SUCCESS = 'ACITIVITY_TABLE_RESPONSE_SUCCESS'
export const ACTIVITY_TABLE_RESPONSE_ERROR = 'ACTIVITY_TABLE_RESPONSE_ERROR'

export const DAY_DETAILS_REQUEST = 'DAY_DETAILS_REQUEST'
export const DAY_DETAILS_RESPONSE = 'DAY_DETAILS_RESPONSE'
export const DAY_DETAILS_RESPONSE_SUCCESS = 'DAY_DETAILS_RESPONSE_SUCCESS'
export const DAY_DETAILS_RESPONSE_ERROR = 'DAY_DETAILS_RESPONSE_ERROR'
